HistoricalFigureCardCatalogRulesTests.Run();
Console.WriteLine("Historical figure card catalogue rules passed.");
HistoricalFigureCardCollectionRulesTests.Run();
Console.WriteLine("Historical figure card collection rules passed.");
HistoricalFigureCardDrawRulesTests.Run();
Console.WriteLine("Historical figure card draw rules passed.");
HistoricalFigureCardDeploymentRulesTests.Run();
HistoricalFigureCardDeploymentServiceSourceGuardTests.Run();
HistoricalFigureCardParentageRulesTests.Run();
Console.WriteLine("Historical figure card deployment rules passed.");
HistoricalFigureCardSourceGuardTests.Run();
Console.WriteLine("Historical figure card source guards passed.");
HistoricalFigureCardAcceptanceSourceGuardTests.Run();
Console.WriteLine("Historical figure card acceptance guards passed.");
