namespace AncientWarfare3.core.lineage
{
    public static class HistoryLocalizationRules
    {
        public static string CurrentLanguage()
        {
            try
            {
                string lang = LocalizedTextManager.current_language?.id;
                return NormalizeLanguage(lang);
            }
            catch
            {
                return "cz";
            }
        }

        public static string NormalizeLanguage(string pLanguage)
        {
            if (string.IsNullOrEmpty(pLanguage)) return "cz";
            string lang = pLanguage.Trim().ToLowerInvariant();
            if (lang == "zh-hant" || lang == "traditional_chinese") return "ch";
            if (lang == "zh-hans" || lang == "simplified_chinese") return "cz";
            if (lang == "en") return "en";
            if (lang == "ch") return "ch";
            return "cz";
        }

        public static string Text(string pKey)
        {
            return Text(pKey, CurrentLanguage());
        }

        public static string Text(string pKey, string pLanguage)
        {
            if (string.IsNullOrEmpty(pKey)) return "";
            string lang = NormalizeLanguage(pLanguage);
            foreach (Entry entry in Entries)
            {
                if (entry.Key != pKey) continue;
                return lang == "en" ? entry.En : lang == "ch" ? entry.Ch : entry.Cz;
            }
            return pKey;
        }

        public static HistoryText H(string pKey)
        {
            return HistoryText.PlainText(Text(pKey));
        }

        public static HistoryText H(string pKey, string pLanguage)
        {
            return HistoryText.PlainText(Text(pKey, pLanguage));
        }

        private readonly struct Entry
        {
            public readonly string Key;
            public readonly string Cz;
            public readonly string En;
            public readonly string Ch;

            public Entry(string pKey, string pCz, string pEn, string pCh)
            {
                Key = pKey;
                Cz = pCz;
                En = pEn;
                Ch = pCh;
            }
        }

        private static readonly Entry[] Entries =
        {
            new Entry("aw_hist_household_principal_wife_accepted",
                "\u5165\u5bab\u4e3a\u6b63\u59bb\uff0c\u914d\u4e8e",
                " entered the court as principal wife of ",
                "\u5165\u5bae\u70ba\u6b63\u59bb\uff0c\u914d\u65bc"),
            new Entry("aw_hist_household_consort_accepted",
                "\u5165\u5bab\u4e3a\u59be\u5ba4\uff0c\u4f8d\u4e8e",
                " entered the court as consort of ",
                "\u5165\u5bae\u70ba\u59be\u5ba4\uff0c\u4f8d\u65bc"),
            new Entry("aw_hist_official_rank_grant_mid", "\u59cb\u6388",
                " is first granted ", "\u59cb\u6388"),
            new Entry("aw_hist_official_rank_grant_suffix",
                "\uff0c\u8457\u5165\u4ed5\u7c4d\u3002",
                " and is entered upon the official register.",
                "\uff0c\u8457\u5165\u4ed5\u7c4d\u3002"),
            new Entry("aw_hist_noble_remarried", "\u7eed\u5f26\u4e8e", " remarried ", "\u7e8c\u5f26\u65bc"),
            new Entry("aw_hist_event_court_surname_granted", "\u8d50\u59d3\u5165\u5b97", "Surname Granted", "\u8cdc\u59d3\u5165\u5b97"),
            new Entry("aw_hist_event_court_lineage_expelled", "\u9664\u7c4d\u522b\u6c0f", "Expelled from Royal Lineage", "\u9664\u7c4d\u5225\u6c0f"),
            new Entry("aw_hist_court_surname_edict", "\u5236\u66f0\uff1a", "Edict: ", "\u5236\u66f0\uff1a"),
            new Entry("aw_hist_court_surname_from", "\u6709\u52b3\u4e8e\u56fd\uff0c\u7279\u8d50\u4ece", " is granted a royal surname and moved from ", "\u6709\u52de\u65bc\u570b\uff0c\u7279\u8cdc\u5f9e"),
            new Entry("aw_hist_court_surname_to", "\u5165", " into ", "\u5165"),
            new Entry("aw_hist_court_surname_by", "\uff0c\u547d\u51fa", " by command of ", "\uff0c\u547d\u51fa"),
            new Entry("aw_hist_court_surname_suffix", "\uff0c\u9644\u5b97\u7c4d\u4ee5\u793a\u4f18\u5ba0\u3002", ". The recipient and patrilineal descendants enter the royal register.", "\uff0c\u9644\u5b97\u7c4d\u4ee5\u793a\u512a\u5bf5\u3002"),
            new Entry("aw_hist_court_expulsion_edict", "\u5236\u66f0\uff1a", "Edict: ", "\u5236\u66f0\uff1a"),
            new Entry("aw_hist_court_expulsion_from", "\u7f6a\u5931\u5b97\u4e49\uff0c\u4eca\u4ece", " is expelled from ", "\u7f6a\u5931\u5b97\u7fa9\uff0c\u4eca\u5f9e"),
            new Entry("aw_hist_court_expulsion_to", "\u9664\u7c4d\uff0c\u53e6\u7acb\u540c\u59d3\u72ec\u7acb\u6c0f\u652f", "; an independent same-surname branch is established as ", "\u9664\u7c4d\uff0c\u53e6\u7acb\u540c\u59d3\u7368\u7acb\u6c0f\u652f"),
            new Entry("aw_hist_court_expulsion_by", "\uff0c\u547d\u51fa", " by command of ", "\uff0c\u547d\u51fa"),
            new Entry("aw_hist_court_expulsion_suffix", "\uff0c\u7236\u5b50\u8c31\u7cfb\u5982\u6545\uff0c\u4e0d\u5f97\u518d\u4e0e\u738b\u7edf\u3002", ". Parent-child descent remains recorded but royal succession rights cease.", "\uff0c\u7236\u5b50\u8b5c\u7cfb\u5982\u6545\uff0c\u4e0d\u5f97\u518d\u8207\u738b\u7d71\u3002"),
            new Entry("aw_hist_shi_suffix", "\u6c0f", " Shi", "\u6c0f"),
            new Entry("aw_hist_unknown_shi", "\u6c0f\u672a\u8be6", "unknown Shi", "\u6c0f\u672a\u8a73"),
            // War and decision labels
            new Entry("aw_hist_label_fabricate_core", "制造核心", "Fabricate Core", "製造核心"),
            new Entry("aw_hist_label_fabricate_weak_claim", "制造弱宣称", "Fabricate Weak Claim", "製造弱宣稱"),
            new Entry("aw_hist_label_fabricate_strong_claim", "制造强宣称", "Fabricate Strong Claim", "製造強宣稱"),
            new Entry("aw_hist_label_core_reclaim", "收复核心", "Reclaim Core", "收復核心"),
            new Entry("aw_hist_label_claim_war", "按宣称宣战", "Claim War", "按宣稱宣戰"),
            new Entry("aw_hist_label_force_vassal", "强制臣服", "Force Vassalization", "強制臣服"),
            new Entry("aw_hist_label_vassal_war", "附庸战争", "Vassal War", "附庸戰爭"),
            new Entry("aw_hist_label_tributary_war", "叩关战争", "Tributary War", "叩關戰爭"),
            new Entry("aw_hist_label_independence_war", "独立战争", "Independence War", "獨立戰爭"),
            new Entry("aw_hist_label_restoration_war", "复国战争", "Restoration War", "復國戰爭"),
            new Entry("aw_hist_label_no_cb", "无理由宣战", "No-CB War", "無理由宣戰"),
            new Entry("aw_hist_label_tianming", "夺取天命", "Seize Mandate", "奪取天命"),
            new Entry("aw_hist_label_mandate_conquest", "天命征服", "Mandate Conquest", "天命征服"),
            new Entry("aw_hist_label_tianmingrebel", "义军天命战争", "Rebel Mandate War", "義軍天命戰爭"),
            new Entry("aw_hist_label_general_rebellion_war", "大将叛乱", "General Rebellion", "大將叛亂"),
            new Entry("aw_hist_label_fief_independence_war", "封地独立", "Fief Independence", "封地獨立"),
            new Entry("aw_hist_label_jingnan_war", "藩王靖难", "Feudatory Jingnan", "藩王靖難"),
            new Entry("aw_hist_label_succession_dispute_war", "宗室争位", "Dynastic Succession War", "宗室爭位"),
            new Entry("aw_hist_label_coup_restoration_war", "勤王复统战争", "Loyalist Restoration War", "勤王復統戰爭"),
            new Entry("aw_hist_event_feudatory_established", "建立藩国", "Feudatory Established", "建立藩國"),
            new Entry("aw_hist_royal_enfeoffment_granted", "分封宗室于", "enfeoffed a royal clansman at ", "分封宗室於"),
            new Entry("aw_hist_royal_enfeoffment_as", "，建立附庸国", ", establishing the vassal realm ", "，建立附庸國"),
            new Entry("aw_hist_royal_enfeoffment_king", "，命", ", appointing ", "，命"),
            new Entry("aw_hist_event_feudatory_inherited", "藩国承袭", "Feudatory Inherited", "藩國承襲"),
            new Entry("aw_hist_event_feudatory_abolished", "绝嗣除国", "Feudatory Abolished", "絕嗣除國"),
            new Entry("aw_hist_event_feudatory_favor", "推恩削藩", "Favor Order Applied", "推恩削藩"),
            new Entry("aw_hist_event_jingnan_started", "藩王靖难", "Feudatory Jingnan", "藩王靖難"),
            new Entry("aw_hist_event_jingnan_suppressed", "靖难平定", "Jingnan Suppressed", "靖難平定"),
            new Entry("aw_hist_event_jingnan_victory", "靖难入主", "Jingnan Accession", "靖難入主"),
            new Entry("aw_hist_event_jingnan_stalemate", "靖难未决", "Jingnan Stalemate", "靖難未決"),
            new Entry("aw_hist_event_noble_rank_granted", "册授爵位", "Noble Rank Granted", "冊授爵位"),
            new Entry("aw_hist_event_noble_rank_inherited", "承袭爵位", "Noble Rank Inherited", "承襲爵位"),
            new Entry("aw_hist_event_noble_rank_extinct", "爵位绝嗣", "Noble Rank Extinct", "爵位絕嗣"),
            new Entry("aw_hist_event_great_royal_grant", "大封宗室", "Great Royal Grant", "大封宗室"),
            new Entry("aw_hist_noble_rank_granted_as", "受册为", " was invested as ", "受冊為"),
            new Entry("aw_hist_noble_rank_granted_by", "，册授者", " by ", "，冊授者"),
            new Entry("aw_hist_noble_rank_inherited_title", "承袭", " inherited the title ", "承襲"),
            new Entry("aw_hist_noble_rank_inherited_from", "，前爵主为", " from ", "，前爵主為"),
            new Entry("aw_hist_noble_rank_extinct_prefix", "所袭", " held the hereditary title ", "所襲"),
            new Entry("aw_hist_noble_rank_extinct_suffix", "，因无合格子嗣而除", " which became extinct for lack of an eligible son", "，因無合格子嗣而除"),
            new Entry("aw_hist_edict_noble_grant_prefix", "制曰：", "Edict: ", "制曰："),
            new Entry("aw_hist_edict_noble_grant_as", "宗支敦睦，勋德有闻，宜册为",
                " has served the royal lineage with distinction and shall be invested as ",
                "宗支敦睦，勳德有聞，宜冊為"),
            new Entry("aw_hist_edict_noble_grant_by", "；其命出于", " by command of ", "；其命出於"),
            new Entry("aw_hist_edict_noble_grant_suffix", "，锡号传家，以昭亲亲之义。",
                "; the honor shall descend in the line.", "，錫號傳家，以昭親親之義。"),
            new Entry("aw_hist_great_royal_grant_prefix", "大封宗室，册授", " invested ", "大封宗室，冊授"),
            new Entry("aw_hist_great_royal_grant_suffix", "人虚爵", " members of the royal clan with titular ranks", "人虛爵"),
            new Entry("aw_hist_edict_great_royal_grant_prefix", "承天建极，敦叙宗盟；今大封宗室，册授",
                " upheld the Mandate and ordered the royal lineage; the court invested ",
                "承天建極，敦敘宗盟；今大封宗室，冊授"),
            new Entry("aw_hist_edict_great_royal_grant_suffix", "人虚爵，使列班序，屏翰王室，以固邦家。",
                " members of the royal clan with titular ranks to uphold the royal house.",
                "人虛爵，使列班序，屏翰王室，以固邦家。"),
            new Entry("aw_hist_edict_fief_grant_prefix", "制曰：", "Edict: ", "制曰："),
            new Entry("aw_hist_edict_fief_grant_mid", "勤劳王事，勋著戎行；今封于",
                " has rendered distinguished service in arms and is hereby enfeoffed at ",
                "勤勞王事，勳著戎行；今封於"),
            new Entry("aw_hist_edict_fief_grant_suffix", "，俾开府治军，镇抚封疆，以屏邦家。",
                "; there to establish a military household and guard the frontier.",
                "，俾開府治軍，鎮撫封疆，以屏邦家。"),
            new Entry("aw_hist_jingnan_started_mid", "以清君侧为名据藩起兵于", " raised the banner of court purification at ", "以清君側為名據藩起兵於"),
            new Entry("aw_hist_jingnan_risk", "；靖难风险：", "; Jingnan risk: ", "；靖難風險："),
            new Entry("aw_hist_jingnan_suppressed_mid", "靖难兵败，旧藩除国于", " was defeated; the former feudatory was abolished at ", "靖難兵敗，舊藩除國於"),
            new Entry("aw_hist_jingnan_victory_mid", "靖难得胜，入主", " won the Jingnan campaign and took the throne of ", "靖難得勝，入主"),
            new Entry("aw_hist_jingnan_victory_suffix", "，本朝易主而国统不绝", "; the dynasty changed ruler without breaking state continuity", "，本朝易主而國統不絕"),
            new Entry("aw_hist_jingnan_stalemate_mid", "靖难未决，仍据地自立为", " ended the Jingnan without decision and retained the claimant realm of ", "靖難未決，仍據地自立為"),
            new Entry("aw_hist_jingnan_stalemate_suffix", "，天下遂入乱世", "; the realm entered an age of disorder", "，天下遂入亂世"),

            new Entry("aw_hist_virtual_title_granted", "授予虚爵：", " granted the virtual title: ", "授予虛爵："),
            new Entry("aw_hist_virtual_title_inherited", "继承虚爵：", " inherited the virtual title: ", "繼承虛爵："),
            new Entry("aw_hist_virtual_title_previous_holder", "，前任为", "; previous holder: ", "，前任為"),
            new Entry("aw_hist_virtual_title_extinct", "虚爵绝嗣：", " virtual title became extinct: ", "虛爵絕嗣："),
            new Entry("aw_hist_noble_title_renamed", "的爵位改为", " changed the noble title to ", "的爵位改為"),
            new Entry("aw_hist_noble_title_renamed_from", "（原为", " (formerly ", "（原為"),
            new Entry("aw_hist_noble_title_deleted", "的爵位被除去：", " had the noble title removed: ", "的爵位被除去："),

            // Event labels
            new Entry("aw_hist_event_war_claim_created", "制造宣称", "Claim Fabricated", "製造宣稱"),
            new Entry("aw_hist_event_war_project_started", "开始战争筹备", "War Project Started", "開始戰爭籌備"),
            new Entry("aw_hist_event_war_project_completed", "完成战争筹备", "War Project Completed", "完成戰爭籌備"),
            new Entry("aw_hist_event_war_goal_set", "设定战争目标", "War Goal Set", "設定戰爭目標"),
            new Entry("aw_hist_event_war_decision", "战争决策", "War Decision", "戰爭決策"),
            new Entry("aw_hist_event_war_start", "战争爆发", "War Began", "戰爭爆發"),
            new Entry("aw_hist_event_war_end", "战争结束", "War Ended", "戰爭結束"),
            new Entry("aw_hist_event_mandate_start", "受命称帝", "Mandate Claimed", "受命稱帝"),
            new Entry("aw_hist_event_mandate_declared_orthodox", "正统受命", "Orthodox Mandate", "正統受命"),
            new Entry("aw_hist_event_mandate_declared_rebel", "义军受命", "Rebel Mandate", "義軍受命"),
            new Entry("aw_hist_event_mandate_declared_foreign_pseudo", "外族伪朝", "Foreign Pseudo-Dynasty", "外族偽朝"),
            new Entry("aw_hist_event_mandate_declared_refounder", "\u590d\u56fd\u53d7\u547d", "Restored Mandate", "\u5fa9\u570b\u53d7\u547d"),
            new Entry("aw_hist_event_mandate_declared_dynastic_restoration", "宗室中兴受命", "Dynastic Restoration", "宗室中興受命"),
            new Entry("aw_hist_event_mandate_declared_player_grant", "\u73a9\u5bb6\u6388\u547d", "Player-Granted Mandate", "\u73a9\u5bb6\u6388\u547d"),
            new Entry("aw_hist_event_accession_book", "册书即位", "Accession Book", "冊書即位"),
            new Entry("aw_hist_event_nine_bestowments", "加九锡", "Nine Bestowments", "加九錫"),
            new Entry("aw_hist_event_official_appointment_edict", "颁授告身", "Appointment Edict", "頒授告身"),
            new Entry("aw_hist_event_ministerial_power_20", "权柄初张", "Ministerial Authority Grew", "權柄初張"),
            new Entry("aw_hist_event_ministerial_power_40", "权臣专政", "Minister Dominated the Court", "權臣專政"),
            new Entry("aw_hist_event_ministerial_power_60", "擅政府朝", "Minister Controlled the Court", "擅政府朝"),
            new Entry("aw_hist_event_ministerial_power_80", "威权震主", "Minister Overshadowed the Ruler", "威權震主"),
            new Entry("aw_hist_event_ministerial_power_90", "逼宫之势", "Palace Coup Threat", "逼宮之勢"),
            new Entry("aw_hist_event_ministerial_palace_coup_success", "权臣篡位", "Ministerial Palace Coup", "權臣篡位"),
            new Entry("aw_hist_event_ministerial_palace_coup_failed", "权臣政变失败", "Ministerial Coup Failed", "權臣政變失敗"),
            new Entry("aw_hist_event_coup_loyalist_rebellion_started", "勤王复统", "Loyalist Restoration Rising", "勤王復統"),
            new Entry("aw_hist_event_coup_loyalist_restoration_victory", "旧统复位", "Old Dynasty Restored", "舊統復位"),
            new Entry("aw_hist_event_coup_loyalist_rebellion_suppressed", "勤王兵败", "Loyalist Rising Suppressed", "勤王兵敗"),
            new Entry("aw_hist_event_coup_loyalist_rebellion_stalemate", "两统并立", "Rival Dynasties Endured", "兩統並立"),
            new Entry("aw_hist_event_royal_claim", "\u590d\u56fd\u5ba3\u79f0", "Restoration Claim", "\u5fa9\u570b\u5ba3\u7a31"),
            new Entry("aw_hist_event_royal_claim_inherited", "\u627f\u7eed\u590d\u56fd\u5ba3\u79f0", "Restoration Claim Inherited", "\u627f\u7e8c\u5fa9\u570b\u5ba3\u7a31"),
            new Entry("aw_hist_event_restoration_kingdom_restored", "\u6276\u6301\u590d\u56fd", "Hosted Restoration", "\u6276\u6301\u5fa9\u570b"),
            new Entry("aw_hist_event_restoration_uprising", "\u4e3e\u5175\u590d\u56fd", "Restoration Uprising", "\u8209\u5175\u5fa9\u570b"),
            new Entry("aw_hist_event_restoration_completed", "\u590d\u56fd\u544a\u6210", "Restoration Completed", "\u5fa9\u570b\u544a\u6210"),
            new Entry("aw_hist_event_restoration_failed", "\u590d\u56fd\u5931\u8d25", "Restoration Failed", "\u5fa9\u570b\u5931\u6557"),
            new Entry("aw_hist_event_mandate_end", "失去天命", "Mandate Lost", "失去天命"),
            new Entry("aw_hist_event_mandate_yearly", "天命年度变化", "Annual Mandate Change", "天命年度變化"),
            new Entry("aw_hist_event_mandate_war_start", "天命战争开始", "Mandate War Began", "天命戰爭開始"),
            new Entry("aw_hist_event_mandate_war_won", "天命战争胜利", "Mandate War Won", "天命戰爭勝利"),
            new Entry("aw_hist_event_mandate_ritual", "祭天整顿", "Mandate Ritual", "祭天整頓"),
            new Entry("aw_hist_event_mandate_sacrifice_auspicious", "大祀获吉", "Auspicious Grand Sacrifice", "大祀獲吉"),
            new Entry("aw_hist_event_mandate_sacrifice_neutral", "大祀平兆", "Neutral Grand Sacrifice", "大祀平兆"),
            new Entry("aw_hist_event_mandate_sacrifice_ominous", "大祀逢凶", "Ominous Grand Sacrifice", "大祀逢凶"),
            new Entry("aw_hist_event_mandate_year_name", "改元", "Era Name Changed", "改元"),
            new Entry("aw_hist_event_mandate_ruler_title", "追上庙谥", "Temple/Posthumous Title", "追上廟諡"),
            new Entry("aw_hist_event_former_king", "亡国之君", "Former Ruler", "亡國之君"),
            new Entry("aw_hist_event_captive_executed", "\u5904\u51b3\u4fd8\u864f", "Captive Executed", "\u8655\u6c7a\u4fd8\u865c"),
            new Entry("aw_hist_event_royal_asylum_started", "\u738b\u65cf\u907f\u96be", "Royal Asylum", "\u738b\u65cf\u907f\u96e3"),
            new Entry("aw_hist_event_royal_asylum_relocated", "\u8f6c\u79fb\u907f\u96be", "Asylum Relocation", "\u8f49\u79fb\u907f\u96e3"),
            new Entry("aw_hist_event_royal_asylum_returned", "\u7ed3\u675f\u907f\u96be", "Returned from Asylum", "\u7d50\u675f\u907f\u96e3"),
            new Entry("aw_hist_event_royal_asylum_naturalized", "\u4ea1\u56fd\u5165\u7c4d", "Naturalized after Realm's Fall", "\u4ea1\u570b\u5165\u7c4d"),
            new Entry("aw_hist_event_mandate_succession_crisis", "继承危机", "Succession Crisis", "繼承危機"),
            new Entry("aw_hist_event_succession_collateral_restore", "恢复宗统", "Lineal Restoration", "恢復宗統"),
            new Entry("aw_hist_event_person_collateral_restore", "恢复宗统", "Lineal Restoration", "恢復宗統"),
            new Entry("aw_hist_event_mandate_collapse", "天命崩解", "Mandate Collapse", "天命崩解"),
            new Entry("aw_hist_event_centralization_reformed", "整饬中央", "Central Reform", "整飭中央"),
            new Entry("aw_hist_event_centralization_chaos_downgrade", "乱世失权", "Central Power Lost", "亂世失權"),
            new Entry("aw_hist_event_vassal_tribute", "岁贡入朝", "Annual Vassal Tribute", "歲貢入朝"),
            new Entry("aw_hist_event_tributary_set", "称臣纳贡", "Tributary Submission", "稱臣納貢"),
            new Entry("aw_hist_event_tributary_get", "受贡册封", "Tributary Received", "受貢冊封"),
            new Entry("aw_hist_event_city_economy_role", "城市经济定位", "City Economic Role", "城市經濟定位"),
            new Entry("aw_hist_event_city_economy_tax", "城市税收", "City Tax", "城市稅收"),
            new Entry("aw_hist_event_court_founded", "官场建立", "Court Founded", "官場建立"),
            new Entry("aw_hist_event_court_officer_appointed", "任官", "Court Appointment", "任官"),
            new Entry("aw_hist_event_court_officer_dismissed", "罢官", "Court Dismissal", "罷官"),
            new Entry("aw_hist_event_court_faction_dominant", "学派主导", "Faction Dominance", "學派主導"),
            new Entry("aw_hist_event_court_city_bureau", "地方官署", "City Bureau", "地方官署"),
            new Entry("aw_hist_event_court_auxiliary_law_changed", "更定辅助法", "Auxiliary Law Changed", "更定輔助法"),
            new Entry("aw_hist_event_inheritance_law_changed", "更定继承法", "Inheritance Law Changed", "更定繼承法"),
            new Entry("aw_hist_event_succession_dispute_started", "宗室争位", "Dynastic Dispute", "宗室爭位"),
            new Entry("aw_hist_event_succession_dispute_resolved", "争位平定", "Dynastic Dispute Resolved", "爭位平定"),
            new Entry("aw_hist_event_succession_permanent_split", "宗统分裂", "Permanent Dynastic Split", "宗統分裂"),
            new Entry("aw_hist_event_succession_reunified", "宗统复合", "Dynastic Reunification", "宗統復合"),
            new Entry("aw_hist_event_heir_designated", "册立继承人", "Heir Designated", "冊立繼承人"),
            new Entry("aw_hist_event_school_disciple", "拜师受业", "Became a Disciple", "拜師受業"),
            new Entry("aw_hist_school_studied_under", "师从", " studied under ", "師從"),
            new Entry("aw_hist_event_school_work_authored", "著述传世", "Work Authored", "著述傳世"),
            new Entry("aw_hist_event_school_conversion", "转投学派", "School Conversion", "轉投學派"),
            new Entry("aw_hist_event_school_rediscovery", "学统复兴", "School Revival", "學統復興"),
            new Entry("aw_hist_event_school_debate", "百家论辩", "School Debate", "百家論辯"),
            new Entry("aw_hist_event_school_master_death", "先师辞世", "Master Died", "先師辭世"),
            new Entry("aw_hist_event_school_master_descent", "先师降临", "Master Appeared", "先師降臨"),
            new Entry("aw_hist_event_school_master_travel", "先师游学", "Master Travelled", "先師遊學"),
            new Entry("aw_hist_event_school_master_arrival", "游学抵达", "Master Arrived", "遊學抵達"),
            new Entry("aw_hist_event_school_guest_service", "客卿任官", "Guest Court Service", "客卿任官"),
            new Entry("aw_hist_school_authored", "著成", " authored ", "著成"),
            new Entry("aw_hist_school_preserved", "传于此城", " and preserved it in this city", "傳於此城"),
            new Entry("aw_hist_school_converted_from", "由", " converted from ", "由"),
            new Entry("aw_hist_school_converted_to", "转入", " to ", "轉入"),
            new Entry("aw_hist_school_rediscovered", "重得", " rediscovered ", "重得"),
            new Entry("aw_hist_school_revived", "复兴", " and revived ", "復興"),
            new Entry("aw_hist_school_debated_with", "与", " debated with ", "與"),
            new Entry("aw_hist_school_debated_topic", "论辩", " on ", "論辯"),
            new Entry("aw_hist_school_outcome_open", "（", " (", "（"),
            new Entry("aw_hist_school_outcome_close", "）", ")", "）"),
            new Entry("aw_hist_school_master_died", "逝世", " died", "逝世"),
            new Entry("aw_hist_school_descended_at", "降临于", " appeared in ", "降臨於"),
            new Entry("aw_hist_school_descended_here", "降临此城", " appeared in this city", "降臨此城"),
            new Entry("aw_hist_school_travelled_to", "游学至", " travelled to study in ", "遊學至"),
            new Entry("aw_hist_school_arrived_to_study", "来此游学", " arrived here to study", "來此遊學"),
            new Entry("aw_hist_school_served_as", "出任", " served as ", "出任"),
            new Entry("aw_hist_school_served_court", "入朝为客卿", " entered court as a guest scholar", "入朝為客卿"),
            new Entry("aw_hist_school_topic_livelihood", "民生", "livelihood", "民生"),
            new Entry("aw_hist_school_topic_famine", "饥荒", "famine", "飢荒"),
            new Entry("aw_hist_school_topic_war", "战争", "war", "戰爭"),
            new Entry("aw_hist_school_topic_defense", "守御", "defense", "守禦"),
            new Entry("aw_hist_school_topic_aggression", "征伐", "aggression", "征伐"),
            new Entry("aw_hist_school_topic_peace", "议和", "peace", "議和"),
            new Entry("aw_hist_school_topic_diplomacy", "外交", "diplomacy", "外交"),
            new Entry("aw_hist_school_topic_order", "治序", "order", "治序"),
            new Entry("aw_hist_school_topic_commerce", "商贸", "commerce", "商貿"),
            new Entry("aw_hist_school_topic_technology", "技艺", "technology", "技藝"),
            new Entry("aw_hist_school_topic_institutions", "制度", "institutions", "制度"),
            new Entry("aw_hist_school_topic_medicine", "医道", "medicine", "醫道"),
            new Entry("aw_hist_school_topic_epidemic", "疫病", "epidemic", "疫病"),
            new Entry("aw_hist_school_outcome_draw", "未分胜负", "no clear victor", "未分勝負"),
            new Entry("aw_hist_school_outcome_narrow_first", "前者小胜", "the former narrowly prevailed", "前者小勝"),
            new Entry("aw_hist_school_outcome_decisive_first", "前者大胜", "the former won decisively", "前者大勝"),
            new Entry("aw_hist_school_outcome_narrow_second", "后者小胜", "the latter narrowly prevailed", "後者小勝"),
            new Entry("aw_hist_school_outcome_decisive_second", "后者大胜", "the latter won decisively", "後者大勝"),
            new Entry("aw_hist_event_border_petition_approved", "准边臣请战", "Border War Petition Approved", "准邊臣請戰"),
            new Entry("aw_hist_event_royal_marriage", "宗室婚盟", "Royal Marriage", "宗室婚盟"),
            new Entry("aw_hist_royal_marriage_mid", "与", " married ", "與"),
            new Entry("aw_hist_royal_marriage_suffix", "缔结婚盟", "", "締結婚盟"),
            new Entry("aw_hist_event_unknown", "未记录", "Unrecorded", "未記錄"),

            new Entry("aw_hist_centralization_reformed_text", "整饬中央，名义集权升至", "Central administration reformed; nominal centralization rose to ", "整飭中央，名義集權升至"),
            new Entry("aw_hist_centralization_chaos_downgrade_text", "乱世失权，名义集权降至", "Chaos weakened central authority; nominal centralization fell to ", "亂世失權，名義集權降至"),
            new Entry("aw_hist_vassal_tribute_text", "收取直属附庸岁贡（政治点 / 黄金）：", " received annual direct-vassal tribute (political points / gold): ", "收取直屬附庸歲貢（政治點 / 黃金）："),
            new Entry("aw_hist_goal_force_tributary", "叩关纳贡", "Compel Tribute", "叩關納貢"),
            new Entry("aw_hist_tributary_set_mid", "向", " began paying annual tribute to ", "向"),
            new Entry("aw_hist_tributary_set_suffix", "称臣纳贡。", ".", "稱臣納貢。"),
            new Entry("aw_hist_tributary_get_mid", "册封", " received ", "冊封"),
            new Entry("aw_hist_tributary_get_suffix", "为朝贡国", " as a tributary", "為朝貢國"),
            new Entry("aw_hist_vassal_set_reason_tributary_war", "战败纳贡于", "submitted in tribute to ", "戰敗納貢於"),
            new Entry("aw_hist_vassal_get_reason_tributary_war", "叩关受贡", "tributary war", "叩關受貢"),

            // Dynamic history text fragments
            new Entry("aw_unknown_kingdom", "\u672a\u77e5\u56fd\u5bb6", "unknown realm", "\u672a\u77e5\u570b\u5bb6"),
            new Entry("aw_hist_asylum_left_home", "\u56e0\u9632\u5fa1\u6218\u4e89\u79bb\u5f00", " left ", "\u56e0\u9632\u79a6\u6230\u722d\u96e2\u958b"),
            new Entry("aw_hist_asylum_went_to", "\uff0c\u524d\u5f80", " for refuge in ", "\uff0c\u524d\u5f80"),
            new Entry("aw_hist_asylum_shelter_suffix", "\u907f\u96be", "", "\u907f\u96e3"),
            new Entry("aw_hist_asylum_relocated_to", "\u8f6c\u5f80", " relocated to ", "\u8f49\u5f80"),
            new Entry("aw_hist_asylum_continue_suffix", "\u7ee7\u7eed\u907f\u96be", " to continue asylum", "\u7e7c\u7e8c\u907f\u96e3"),
            new Entry("aw_hist_asylum_returned_to", "\u7ed3\u675f\u907f\u96be\uff0c\u8fd4\u56de", " ended asylum and returned to ", "\u7d50\u675f\u907f\u96e3\uff0c\u8fd4\u56de"),
            new Entry("aw_hist_asylum_after_home_fall", "\u5728", ", after ", "\u5728"),
            new Entry("aw_hist_asylum_joined_host", "\u8986\u4ea1\u540e\u52a0\u5165", " fell, joined ", "\u8986\u4ea1\u5f8c\u52a0\u5165"),
            new Entry("aw_hist_asylum_settled_at", "\uff0c\u5b9a\u5c45\u4e8e", " and settled in ", "\uff0c\u5b9a\u5c45\u65bc"),
            new Entry("aw_court_school_none", "\u65e0\u5b66\u6d3e", "No school", "\u7121\u5b78\u6d3e"),
            new Entry("aw_heir_shizi", "\u4e16\u5b50", "Heir", "\u4e16\u5b50"),
            new Entry("aw_heir_taizi", "\u592a\u5b50", "Crown Prince", "\u592a\u5b50"),
            new Entry("aw_heir_liuhou", "\u7559\u540e", "Military Heir", "\u7559\u5f8c"),
            new Entry("aw_heir_sijun", "\u55e3\u541b", "Designated Successor", "\u55e3\u541b"),
            new Entry("aw_court_school_primitive", "\u4e1c\u5468\u671d\u81e3", "Eastern Zhou courtier", "\u6771\u5468\u671d\u81e3"),
            new Entry("aw_court_school_ru", "\u5112\u5bb6", "Ru school", "\u5112\u5bb6"),
            new Entry("aw_court_school_fa", "\u6cd5\u5bb6", "Legalist school", "\u6cd5\u5bb6"),
            new Entry("aw_court_school_dao", "\u9053\u5bb6", "Dao school", "\u9053\u5bb6"),
            new Entry("aw_court_school_mo", "\u58a8\u5bb6", "Mohist school", "\u58a8\u5bb6"),
            new Entry("aw_court_school_bing", "\u5175\u5bb6", "Military school", "\u5175\u5bb6"),
            new Entry("aw_court_school_zongheng", "\u7eb5\u6a2a\u5bb6", "Diplomat school", "\u7e31\u6a6b\u5bb6"),
            new Entry("aw_court_school_nong", "\u519c\u5bb6", "Agrarian school", "\u8fb2\u5bb6"),
            new Entry("aw_court_school_yinyang", "\u9634\u9633\u5bb6", "Yin-Yang school", "\u9670\u967d\u5bb6"),
            new Entry("aw_court_school_ming", "\u540d\u5bb6", "Logician school", "\u540d\u5bb6"),
            new Entry("aw_court_school_medical", "\u533b\u5bb6", "Medical school", "\u91ab\u5bb6"),
            new Entry("aw_court_school_syncretist", "\u6742\u5bb6", "Syncretist school", "\u96dc\u5bb6"),
            new Entry("aw_court_school_merchant", "\u5546\u5bb6", "Merchant school", "\u5546\u5bb6"),
            new Entry("aw_court_school_craftsman", "\u5de5\u5bb6", "Craftsman school", "\u5de5\u5bb6"),
            new Entry("aw_court_school_historian", "\u53f2\u5bb6", "Historian school", "\u53f2\u5bb6"),
            new Entry("aw_hist_royal_medical_cure_mid", "\u7ecf\u592a\u533b\u4ee4", " was cured by Imperial Physician ", "\u7d93\u592a\u91ab\u4ee4"),
            new Entry("aw_hist_royal_medical_cure_suffix", "\u8bca\u6cbb\uff0c\u75c5\u75c7\u5f97\u6108", " and recovered from a curable illness", "\u8a3a\u6cbb\uff0c\u75c5\u75c7\u5f97\u7652"),
            new Entry("aw_hist_court_founded_official", " 建立百家官场", " established a Court of the Hundred Schools", " 建立百家官場"),
            new Entry("aw_hist_court_tier_mid", " 官制改革,升为", " reformed its court into ", " 官制改革,升為"),
            new Entry("aw_hist_edict_court_tier_mid", "诏整官制，因时立法；今升为",
                " decreed a reform of institutions and raised the court to ",
                "詔整官制，因時立法；今升為"),
            new Entry("aw_hist_edict_court_tier_suffix", "，分职厘务，百官各守其序。",
                "; offices were divided and ordered according to their charge.",
                "，分職釐務，百官各守其序。"),
            new Entry("aw_hist_edict_court_institution_mid", "诏因时改制，参酌古今；今定官政为",
                " decreed an institutional reform and established the ",
                "詔因時改制，參酌古今；今定官政為"),
            new Entry("aw_hist_edict_court_institution_suffix", "，厘正文武财计，百司各循新章。",
                "; civil military and fiscal offices were ordered under the new code.",
                "，釐正文武財計，百司各循新章。"),
            new Entry("aw_hist_court_founded_primitive", " 设立东周六卿", " established the Eastern Zhou Six Ministers", " 設立東周六卿"),
            new Entry("aw_hist_court_auxiliary_law_changed_mid", "诏更定", " decreed a change to ", "詔更定"),
            new Entry("aw_hist_court_auxiliary_law_from", "，由", ", from ", "，由"),
            new Entry("aw_hist_court_auxiliary_law_to", "改为", " to ", "改為"),
            new Entry("aw_hist_inheritance_law_changed_mid", "诏更定继承法，由", " decreed that succession change from ", "詔更定繼承法，由"),
            new Entry("aw_hist_inheritance_law_changed_to", "改为", " to ", "改為"),
            new Entry("aw_hist_goal_reunify_succession", "统一宗统", "Reunify the Dynasty", "統一宗統"),
            new Entry("aw_hist_succession_dispute_claimed_mid", "不服新君，举兵争夺", " rejected the new ruler and rose to contest ", "不服新君，舉兵爭奪"),
            new Entry("aw_hist_succession_dispute_founded_mid", "，另立", ", establishing ", "，另立"),
            new Entry("aw_hist_succession_dispute_defeated_mid", "平定与", " ended the contest with ", "平定與"),
            new Entry("aw_hist_succession_claimant_won_suffix", "之争，争位者入承原统。", "; the claimant inherited the original realm.", "之爭，爭位者入承原統。"),
            new Entry("aw_hist_succession_successor_won_suffix", "之争，新君守住宗统。", "; the installed ruler preserved the succession.", "之爭，新君守住宗統。"),
            new Entry("aw_hist_succession_split_with_mid", "与", " and ", "與"),
            new Entry("aw_hist_succession_split_suffix", "相持十二年，宗统遂分；双方三代内保有无费统一宣称。", " remained divided for twelve years; both lines retain a free reunification claim for three generations.", "相持十二年，宗統遂分；雙方三代內保有無費統一宣稱。"),
            new Entry("aw_hist_succession_reunified_mid", "统一", " reunified ", "統一"),
            new Entry("aw_hist_succession_reunified_and_mid", "与", " and ", "與"),
            new Entry("aw_hist_succession_reunified_suffix", "，仍承原国统与原 Kingdom ID。", ", preserving the original realm and Kingdom ID.", "，仍承原國統與原 Kingdom ID。"),
            new Entry("aw_hist_heir_designated_mid", "册立", " designated ", "冊立"),
            new Entry("aw_hist_heir_designated_as", "为", " as ", "為"),
            new Entry("aw_inheritance_control_automatic", "因时议定", "automatic evaluation", "因時議定"),
            new Entry("aw_inheritance_law_primogeniture", "嫡长继承", "primogeniture", "嫡長繼承"),
            new Entry("aw_inheritance_law_military", "军中拥立", "military acclaim", "軍中擁立"),
            new Entry("aw_inheritance_law_civil", "\u6587\u5b98\u62e5\u7acb", "civil acclaim", "\u6587\u5b98\u64c1\u7acb"),
            new Entry("aw_hist_border_petition_source_mid", "准", " approved the war petition of ", "准"),
            new Entry("aw_hist_border_petition_target_mid", "所请，对", " against ", "所請，對"),
            new Entry("aw_hist_border_petition_reason_mid", "以", " on the grounds of ", "以"),
            new Entry("aw_hist_border_petition_suffix", "发出战书", " and issued a declaration of war", "發出戰書"),
            new Entry("aw_court_aux_law_term", "任期法", "Term Law", "任期法"),
            new Entry("aw_court_aux_law_border", "边防之制", "Border Command Law", "邊防之制"),
            new Entry("aw_court_aux_law_appointment", "用官文化", "Appointment Culture", "用官文化"),
            new Entry("aw_court_aux_law_conscription", "\u5f81\u5175\u6cd5", "Conscription Law", "\u5fb5\u5175\u6cd5"),
            new Entry("aw_court_term_lifetime", "终身任期", "Lifetime Tenure", "終身任期"),
            new Entry("aw_court_term_three", "固定三年", "Fixed Three Years", "固定三年"),
            new Entry("aw_court_term_dynamic", "动态三至六年", "Dynamic Three to Six Years", "動態三至六年"),
            new Entry("aw_court_term_nine", "固定九年", "Fixed Nine Years", "固定九年"),
            new Entry("aw_court_border_discretionary", "便宜行事", "Discretionary Action", "便宜行事"),
            new Entry("aw_court_border_petition", "上书请战", "Petition for War", "上書請戰"),
            new Entry("aw_court_border_centralized", "兵权归中", "Centralized Command", "兵權歸中"),
            new Entry("aw_court_appointment_merit", "唯才是举", "Merit Only", "唯才是舉"),
            new Entry("aw_court_appointment_preference", "Xia优先", "Xia Preference", "Xia優先"),
            new Entry("aw_court_appointment_centered", "Xia中心", "Xia-Centered", "Xia中心"),
            new Entry("aw_court_conscription_limited", "\u6709\u9650\u5f81\u53d1", "Limited Levy", "\u6709\u9650\u5fb5\u767c"),
            new Entry("aw_court_conscription_standard", "\u5e38\u5236\u5f81\u5175", "Standard Conscription", "\u5e38\u5236\u5fb5\u5175"),
            new Entry("aw_court_conscription_expanded", "\u6269\u5927\u5f81\u53d1", "Expanded Levy", "\u64f4\u5927\u5fb5\u767c"),
            new Entry("aw_court_conscription_full", "\u5168\u9762\u52a8\u5458", "Full Mobilization", "\u5168\u9762\u52d5\u54e1"),
            new Entry("aw_hist_decline_rebel_rose_at", " 于", " rose at ", " 於"),
            new Entry("aw_hist_decline_rebel_against", " 据城起兵反抗", " in local rebellion against ", " 據城起兵反抗"),
            new Entry("aw_hist_court_entered_as", " 入朝为", " entered court as ", " 入朝為"),
            new Entry("aw_hist_court_school_mid", "，属", ", aligned with ", "，屬"),
            new Entry("aw_hist_court_dominant_mid", " 官场由", "'s court was dominated by ", " 官場由"),
            new Entry("aw_hist_court_dominant_suffix", "主导", "", "主導"),
            new Entry("aw_hist_court_dismissed_mid", " 被免去", " was dismissed from ", " 被免去"),
            new Entry("aw_hist_court_reform_mid", " 官场变法，由", "'s court underwent a major reform led by ", " 官場變法，由"),
            new Entry("aw_hist_court_reform_suffix", " 主导推行", " ", " 主導推行"),
            new Entry("aw_hist_edict_court_reform_mid", "诏令更张官政，因治制宜；今命",
                " decreed a reform of government and appointed ",
                "詔令更張官政，因治制宜；今命"),
            new Entry("aw_hist_edict_court_reform_suffix", "主导变法，修典章，正百职，以经邦国。",
                " to lead it; institutions and offices were set in order.",
                "主導變法，修典章，正百職，以經邦國。"),
            new Entry("aw_hist_court_bureau_mid", " 改组地方官署 ", " reorganized the local bureau of ", " 改組地方官署 "),
            new Entry("aw_hist_court_bureau_suffix", "，主理学派为", ", led by ", "，主理學派為"),
            new Entry("aw_hist_king_ascended", " 即位为君", " ascended as ruler", " 即位為君"),
            new Entry("aw_hist_person_ascended_prefix", " 即位为 ", " ascended as ruler of ", " 即位為 "),
            new Entry("aw_hist_person_ascended_suffix", " 之君", "", " 之君"),
            new Entry("aw_hist_lost_throne", " 失位", " lost the throne", " 失位"),
            new Entry("aw_hist_collateral_restore_mid", "由旁系入继，恢复", " entered by collateral succession and restored ", "由旁系入繼，恢復"),
            new Entry("aw_hist_collateral_restore_suffix", "宗统", " legitimacy", "宗統"),
            new Entry("aw_hist_nonagnatic_succession", " 以异姓入继大统", " succeeded to the throne from a different clan", " 以異姓入繼大統"),
            new Entry("aw_hist_previous_ruler_prefix", "（前君 ", " (former ruler ", "（前君 "),
            new Entry("aw_hist_paren_open", "（", " (", "（"),
            new Entry("aw_hist_paren_close", "）", ")", "）"),
            new Entry("aw_hist_colon", "：", ": ", "："),
            new Entry("aw_hist_old_shi", "旧", "old", "舊"),
            new Entry("aw_hist_kingdom_founded_suffix", " 建立", " was founded", " 建立"),
            new Entry("aw_hist_kingdom_destroyed_suffix", " 灭亡", " was destroyed", " 滅亡"),
            new Entry("aw_hist_abdicated", " 退位", " abdicated", " 退位"),
            new Entry("aw_hist_slave_abdicated_prefix", " 因沦为奴隶退位（", " abdicated after being enslaved (", " 因淪為奴隸退位（"),
            new Entry("aw_hist_belongs_to_prefix", "隶属于 ", "belonging to ", "隸屬於 "),
            new Entry("aw_hist_belongs_to_suffix", " 的", " ", " 的"),
            new Entry("aw_hist_city_founded_prefix", " 作为", " was founded as a ", " 作為"),
            new Entry("aw_hist_city_founded_suffix", "城市建立", " city", "城市建立"),
            new Entry("aw_hist_city_left_owner", " 脱离", " left ", " 脫離"),
            new Entry("aw_hist_city_became_unowned", "，成为无所属城市", " and became unowned", "，成為無所屬城市"),
            new Entry("aw_hist_lost_city_prefix", "失去 ", "Lost ", "失去 "),
            new Entry("aw_hist_city_abandoned_note", "（城市废弃或无所属）", " (city abandoned or unowned)", "（城市廢棄或無所屬）"),
            new Entry("aw_hist_city_joined", " 归属", " joined ", " 歸屬"),
            new Entry("aw_hist_gained_city_prefix", "夺得 ", "Gained ", "奪得 "),
            new Entry("aw_hist_city_former_unowned_note", "（原为无所属城市）", " (formerly unowned)", "（原為無所屬城市）"),
            new Entry("aw_hist_city_transfer_from", " 由 ", " from ", " 由 "),
            new Entry("aw_hist_city_transfer_to", " 易主至 ", " transferred to ", " 易主至 "),
            new Entry("aw_hist_city_to_kingdom_prefix", "(归 ", " (to ", "(歸 "),
            new Entry("aw_hist_city_from_kingdom_prefix", "(原属 ", " (from ", "(原屬 "),
            new Entry("aw_hist_war_with_prefix", "与 ", "War with ", "與 "),
            new Entry("aw_hist_war_started", " 爆发战争", " began", " 爆發戰爭"),
            new Entry("aw_hist_war_started_named_open",
                " \u7206\u53d1\u6218\u4e89\uff08", " began (",
                " \u7206\u767c\u6230\u722d\uff08"),
            new Entry("aw_hist_war_started_named_close",
                "\uff09", ")", "\uff09"),
            new Entry("aw_hist_war_ended_mid", " 的战争结束:", " ended: ", " 的戰爭結束："),
            new Entry("aw_hist_war_notice_issued_mid", "致战书于", " issued a declaration of war to ", "致戰書於"),
            new Entry("aw_hist_war_notice_received_mid", "收到战书，来自", " received a declaration of war from ", "收到戰書，來自"),
            new Entry("aw_hist_temporary_levy_enlisted", "奉召临时入伍", " was temporarily levied", "奉召臨時入伍"),
            new Entry("aw_hist_temporary_levy_demobilized", "战后解除征召", " was released from wartime levy", "戰後解除徵召"),
            new Entry("aw_hist_temporary_slave_vanguard_demobilized", "解散了临时奴隶先锋军", " disbanded its temporary slave vanguard", "解散了臨時奴隸先鋒軍"),
            new Entry("aw_hist_war_claim_created_mid", " 取得对", " gained a casus belli against ", " 取得對"),
            new Entry("aw_hist_war_claim_created_reason", "的宣战理由：", ": ", "的宣戰理由："),
            new Entry("aw_hist_no_cb_war_mid", " 无故兴兵，攻伐", " attacked without cause: ", " 無故興兵，攻伐"),
            new Entry("aw_hist_war_decision_with", " 以", " declared war with ", " 以"),
            new Entry("aw_hist_war_decision_against", " 对", " against ", " 對"),
            new Entry("aw_hist_war_decision_suffix", " 开战", "", " 開戰"),
            new Entry("aw_hist_son", "子", "son", "子"),
            new Entry("aw_hist_daughter", "女", "daughter", "女"),
            new Entry("aw_hist_had_child", " 喜得", " had a ", " 喜得"),
            new Entry("aw_hist_enfeoffed_leader_prefix", " 受封为 ", " was appointed leader of ", " 受封為 "),
            new Entry("aw_hist_city_leader_suffix", " 城主", "", " 城主"),
            new Entry("aw_hist_became_clan_chief", " 成为家主", " became clan chief", " 成為家主"),
            new Entry("aw_hist_exiled_from_clan", " 被逐出氏族", " was exiled from the clan", " 被逐出氏族"),
            new Entry("aw_hist_joined_clan", " 加入氏族 ", " joined clan ", " 加入氏族 "),
            new Entry("aw_hist_clan_fallback", "氏族", "clan", "氏族"),
            new Entry("aw_hist_someone", "某人", "someone", "某人"),
            new Entry("aw_hist_rebelled", " 起兵反叛", " raised a rebellion", " 起兵反叛"),
            new Entry("aw_hist_rebelled_in_realm", " 在境内起兵反叛", " rebelled within the realm", " 在境內起兵反叛"),
            new Entry("aw_hist_enlisted", " 入伍从军", " enlisted as a soldier", " 入伍從軍"),
            new Entry("aw_hist_enslaved", " 沦为奴隶（", " was enslaved (", " 淪為奴隸（"),
            new Entry("aw_hist_captured_as_slave", " 被俘获为奴（", " was captured as a slave (", " 被俘獲為奴（"),
            new Entry("aw_hist_in_city", " 在 ", " in ", " 在 "),
            new Entry("aw_hist_registered_slave", " 被编入奴籍（", " was registered as a slave (", " 被編入奴籍（"),
            new Entry("aw_hist_as_former_ruler_mid", "以", "as ruler of ", "以"),
            new Entry("aw_hist_ruler_of_former_kingdom", "君主之身被", " was captured by ", "君主之身被"),
            new Entry("aw_hist_captured_enslaved", "俘获，沦为奴隶（", " and enslaved (", "俘獲，淪為奴隸（"),
            new Entry("aw_hist_captor_prefix", "，俘获者 ", ", captor ", "，俘獲者 "),
            new Entry("aw_hist_placed_in_city", "，安置于", ", settled in ", "，安置於"),
            new Entry("aw_hist_enemy_realm", "敌国", "enemy realm", "敵國"),
            new Entry("aw_hist_freed_slave", " 脱离奴籍，成为平民（", " was freed from slavery and became a commoner (", " 脫離奴籍，成為平民（"),
            new Entry("aw_hist_freed_slave_short", " 脱离奴籍（", " was freed from slavery (", " 脫離奴籍（"),
            new Entry("aw_hist_city_freed_slave", " 脱离奴籍（", " was freed from slavery (", " 脫離奴籍（"),
            new Entry("aw_hist_captive_noble_title", "客卿", "Noble Dependent", "客卿"),
            new Entry("aw_hist_captive_noble_released", " 脱离奴籍，以客卿安置（", " was freed from slavery and kept as a noble dependent (", " 脫離奴籍，以客卿安置（"),
            new Entry("aw_hist_captive_noble_city_released", " 以客卿安置（", " was kept as a noble dependent (", " 以客卿安置（"),
            new Entry("aw_hist_captive_executed_mid", " \u88ab\u4fd8\u540e\u5904\u51b3\uff08", " was executed after capture (", " \u88ab\u4fd8\u5f8c\u8655\u6c7a\uff08"),
            new Entry("aw_hist_captive_executed_school_mid", "\uff0c\u7531", ", under the influence of ", "\uff0c\u7531"),
            new Entry("aw_hist_captive_executed_school_suffix", "\u4e3b\u5bfc", "", "\u4e3b\u5c0e"),
            new Entry("aw_hist_captive_executed_former_mid", " \u88ab", " was executed by ", " \u88ab"),
            new Entry("aw_hist_captive_executed_former_suffix", "\u5904\u51b3", "", "\u8655\u6c7a"),
            new Entry("aw_hist_captive_executed_captor_mid", " \u5904\u51b3\u91cd\u8981\u4fd8\u864f", " executed important captive ", " \u8655\u6c7a\u91cd\u8981\u4fd8\u865c"),
            new Entry("aw_hist_captive_executed_captor_suffix", "\uff0c\u65f6\u5b98\u573a\u4e3b\u5bfc\u4e3a", "; dominant court school: ", "\uff0c\u6642\u5b98\u5834\u4e3b\u5c0e\u70ba"),
            new Entry("aw_death_cause_captive_execution", "\u4fd8\u540e\u88ab\u5904\u51b3", "executed after capture", "\u4fd8\u5f8c\u88ab\u8655\u6c7a"),
            new Entry("aw_death_cause_captive_execution_school", "\uff1b\u4e3b\u5bfc\u5b66\u6d3e\uff1a", "; school: ", "\uff1b\u4e3b\u5c0e\u5b78\u6d3e\uff1a"),
            new Entry("aw_death_cause_captive_execution_by", "\uff1b\u6267\u884c\u8005\uff1a", "; executor: ", "\uff1b\u57f7\u884c\u8005\uff1a"),
            new Entry("aw_hist_retired_soldier", " 退伍为老兵，不再应征", " retired as a veteran and will not be conscripted again", " 退伍為老兵，不再應徵"),
            new Entry("aw_hist_retired_from_city", " 自 ", " retired from ", " 自 "),
            new Entry("aw_hist_retired_from_city_suffix", " 退伍", "", " 退伍"),
            new Entry("aw_hist_slave_enlisted", " 以奴隶兵身份入伍", " enlisted as a slave soldier", " 以奴隸兵身份入伍"),
            new Entry("aw_hist_slave_army_joined", " 被编入奴隶军", " was assigned to the slave army", " 被編入奴隸軍"),
            new Entry("aw_hist_merit_prefix", "立下军功 ", "earned ", "立下軍功 "),
            new Entry("aw_hist_merit_mid", " 点，累计 ", " merit points, total ", " 點，累計 "),
            new Entry("aw_hist_merit_suffix", " 点", " points", " 點"),
            new Entry("aw_hist_slave_soldier", " 奴隶兵", " slave soldier ", " 奴隸兵"),
            new Entry("aw_hist_slave_army_formed", " 开始编组奴隶军", " began organizing a slave army", " 開始編組奴隸軍"),
            new Entry("aw_hist_slave_labor_started_prefix", " 登记奴隶劳役，奴隶 ", " registered slave labor: ", " 登記奴隸勞役，奴隸 "),
            new Entry("aw_hist_people_count", " 人", " people", " 人"),
            new Entry("aw_hist_war_slave_capture_prefix", " 在战争结算中俘获奴隶 ", " captured ", " 在戰爭結算中俘獲奴隸 "),
            new Entry("aw_hist_war_slave_capture_mid", " 名，安置于 ", " slaves in the war settlement and settled them in ", " 名，安置於 "),
            new Entry("aw_hist_city_war_slave_capture_prefix", " 安置战争俘获奴隶 ", " settled ", " 安置戰爭俘獲奴隸 "),
            new Entry("aw_hist_city_war_slave_capture_suffix", " 名", " captured slaves", " 名"),
            new Entry("aw_hist_royal_guard_default", "禁卫军", "Royal Guard", "禁衛軍"),
            new Entry("aw_hist_royal_guard_founded", " 设立", " established ", " 設立"),
            new Entry("aw_hist_royal_guard_captain", "统领", "captained ", "統領"),
            new Entry("aw_hist_royal_guard_member", "入选", "joined ", "入選"),
            new Entry("aw_hist_royal_guard_in_city_mid", " 在", " in ", " 在"),
            new Entry("aw_hist_left_royal_guard", " 离开禁卫军（", " left the Royal Guard (", " 離開禁衛軍（"),
            new Entry("aw_hist_killed", " 击杀了 ", " killed ", " 擊殺了 "),
            new Entry("aw_hist_was_killed_by", " 为 ", " was killed by ", " 為 "),
            new Entry("aw_hist_was_killed_by_suffix", " 所杀", "", " 所殺"),
            new Entry("aw_hist_fell_in_love", " 与 ", " fell in love with ", " 與 "),
            new Entry("aw_hist_fell_in_love_suffix", " 坠入爱河", "", " 墜入愛河"),
            new Entry("aw_hist_partner", "伴侣", "partner", "伴侶"),
            new Entry("aw_hist_relative", "亲人", "relative", "親人"),
            new Entry("aw_hist_lost_bond", " 痛失", " mourned the loss of ", " 痛失"),

            // Reason labels
            new Entry("aw_hist_slave_reason_city_fall", "城破被俘", "captured when the city fell", "城破被俘"),
            new Entry("aw_hist_slave_reason_captured", "俘获", "captured", "俘獲"),
            new Entry("aw_hist_slave_reason_battlefield_capture", "战场俘获", "captured on the battlefield", "戰場俘獲"),
            new Entry("aw_hist_slave_reason_foreign_occupation", "外族占领", "foreign occupation", "外族佔領"),
            new Entry("aw_hist_slave_reason_slave_king", "国王为奴", "enslaved king", "國王為奴"),
            new Entry("aw_hist_slave_reason_slave_only_rebel", "奴隶国改编为义军", "slave-only realm reorganized as rebels", "奴隸國改編為義軍"),
            new Entry("aw_hist_slave_reason_born_slave", "奴籍所生", "born into slavery", "奴籍所生"),
            new Entry("aw_hist_slave_reason_military_merit", "军功释奴", "freed by military merit", "軍功釋奴"),
            new Entry("aw_hist_slave_reason_promoted", "因受任官职释奴", "freed by appointment to office", "因受任官職釋奴"),
            new Entry("aw_hist_slave_reason_noble_dependent", "礼制安置", "ritual noble placement", "禮制安置"),
            new Entry("aw_hist_slave_reason_registered", "奴籍登记", "slave registration", "奴籍登記"),
            new Entry("aw_hist_guard_reason_died", "战死或身故", "dead", "戰死或身故"),
            new Entry("aw_hist_guard_reason_no_king", "无在位君主", "no reigning ruler", "無在位君主"),
            new Entry("aw_hist_guard_reason_no_noble_captain", "无贵族统领", "no noble captain", "無貴族統領"),
            new Entry("aw_hist_guard_reason_over_limit", "名额调整", "roster adjustment", "名額調整"),
            new Entry("aw_hist_guard_reason_invalid", "资格不符", "ineligible", "資格不符"),
            new Entry("aw_hist_guard_reason_enslaved", "沦为奴隶", "enslaved", "淪為奴隸"),
            new Entry("aw_hist_guard_reason_became_leader", "受任城主", "appointed city leader", "受任城主"),
            new Entry("aw_hist_guard_reason_left", "离任", "left office", "離任"),

            // Vassal history text
            new Entry("aw_hist_vassal_absorb_mid", " 吞并附庸 ", " annexed vassal ", " 吞併附庸 "),
            new Entry("aw_hist_vassal_absorbed_mid", " 被 ", " was annexed by ", " 被 "),
            new Entry("aw_hist_vassal_absorbed_suffix", " 吞并", "", " 吞併"),
            new Entry("aw_hist_vassal_became_suffix", "，成为附庸", ", becoming a vassal", "，成為附庸"),
            new Entry("aw_hist_vassal_get_mid", " 收 ", " accepted ", " 收 "),
            new Entry("aw_hist_vassal_get_suffix", " 为附庸", " as a vassal", " 為附庸"),
            new Entry("aw_hist_vassal_independence_war_verb", "通过独立战争脱离", "broke from", "通過獨立戰爭脫離"),
            new Entry("aw_hist_vassal_left_verb", "脱离", "left", "脫離"),
            new Entry("aw_hist_vassal_independent_suffix", " 独立", " and became independent", " 獨立"),
            new Entry("aw_hist_vassal_suzerain_fallback", "宗主国", "suzerain", "宗主國"),
            new Entry("aw_hist_vassal_lost_mid", " 失去附庸 ", " lost vassal ", " 失去附庸 "),
            new Entry("aw_hist_vassal_fell_suffix", "（亡国）", " (destroyed)", "（亡國）"),
            new Entry("aw_hist_vassal_suzerain_fell_mid", " 因宗主 ", " regained independence after suzerain ", " 因宗主 "),
            new Entry("aw_hist_vassal_suzerain_fell_suffix", " 灭亡而恢复独立", " fell", " 滅亡而恢復獨立"),
            new Entry("aw_hist_vassal_set_reason_active", "因外部威胁主动臣属于 ", "voluntarily submitted to ", "因外部威脅主動臣屬於 "),
            new Entry("aw_hist_vassal_set_reason_war", "战败后臣属于 ", "submitted after defeat to ", "戰敗後臣屬於 "),
            new Entry("aw_hist_vassal_set_reason_reparent", "因附庸体系重整转臣属于 ", "was reassigned under ", "因附庸體系重整轉臣屬於 "),
            new Entry("aw_hist_vassal_set_reason_suzerain_fell", "因旧宗主灭亡改臣属于 ", "changed allegiance to ", "因舊宗主滅亡改臣屬於 "),
            new Entry("aw_hist_vassal_set_reason_manual", "臣属于 ", "submitted to ", "臣屬於 "),
            new Entry("aw_hist_vassal_get_reason_active", "主动臣属", "voluntary submission", "主動臣屬"),
            new Entry("aw_hist_vassal_get_reason_war", "战争臣服", "war submission", "戰爭臣服"),
            new Entry("aw_hist_vassal_get_reason_reparent", "体系重整", "vassal system reorganization", "體系重整"),
            new Entry("aw_hist_vassal_get_reason_suzerain_fell", "改投宗主", "changed suzerain", "改投宗主"),
            new Entry("aw_hist_vassal_get_reason_manual", "上帝设定", "manual setting", "上帝設定"),
            new Entry("aw_hist_vassal_get_reason_generic", "臣属", "submission", "臣屬"),
            new Entry("aw_hist_former_king_title_common", "亡国之君", "Former Ruler", "亡國之君"),
            new Entry("aw_hist_former_king_at", "在", " after ", "在"),
            new Entry("aw_hist_former_king_after_fall_mid", "灭亡后成为", " became ", "滅亡後成為"),
            new Entry("aw_hist_former_king_fell", "", " fell", ""),
            new Entry("aw_hist_mandate_ruler_title_mid", " 追上天命庙谥：", " received Mandate temple/posthumous title: ", " 追上天命廟諡："),
            new Entry("aw_hist_general_high_risk_person", " 拥兵自重，朝野侧目", " held troops independently and alarmed the court", " 擁兵自重，朝野側目"),
            new Entry("aw_hist_general_high_risk_kingdom", " 拥兵自重，风险 ", " held troops independently, risk ", " 擁兵自重，風險 "),
            new Entry("aw_hist_general_in_city", " 在", " in ", " 在"),
            new Entry("aw_hist_general_high_risk_city", " 拥兵自重", " held troops independently", " 擁兵自重"),
            new Entry("aw_hist_general_based_on", " 据", " used ", " 據"),
            new Entry("aw_hist_general_self_rule", " 起兵自立", " as a base and rose independently", " 起兵自立"),
            new Entry("aw_hist_general_rebelled", " 起兵叛乱", " raised a rebellion", " 起兵叛亂"),
            new Entry("aw_hist_general_founded_by", " 由", " was founded by ", " 由"),
            new Entry("aw_hist_general_rebel_founded", " 起兵建立", " in rebellion", " 起兵建立"),
            new Entry("aw_hist_general_became", " 成为", " became ", " 成為"),
            new Entry("aw_hist_general_rebel_base", " 叛军根据地", "'s rebel base", " 叛軍根據地"),
            new Entry("aw_hist_general_palace_coup_success", " 发动逼宫并夺取王位", " staged a palace coup and seized the throne", " 發動逼宮並奪取王位"),
            new Entry("aw_hist_general_palace_coup_failed", " 发动逼宫失败", " staged a failed palace coup", " 發動逼宮失敗"),
            new Entry("aw_hist_coup_loyalist_supports", "不承认新君，拥立", " rejected the usurper and acclaimed ", "不承認新君，擁立"),
            new Entry("aw_hist_coup_loyalist_rose_at", "起兵于", " and raised loyalist forces at ", "起兵於"),
            new Entry("aw_hist_coup_loyalist_score", "；拥立声势：", "; loyalist strength: ", "；擁立聲勢："),
            new Entry("aw_hist_coup_loyalist_restored", "平定权臣，复位于", " defeated the usurper and returned to the throne of ", "平定權臣，復位於"),
            new Entry("aw_hist_coup_loyalist_restored_suffix", "，旧宗统得续", "; the old royal succession continued", "，舊宗統得續"),
            new Entry("aw_hist_coup_loyalist_suppressed", "勤王兵败，旧宗室未能复位：", " was defeated; the old dynasty was not restored: ", "勤王兵敗，舊宗室未能復位："),
            new Entry("aw_hist_coup_loyalist_stalemate", "复统未决，仍据地自立为", " failed to decide the succession and retained the rival realm of ", "復統未決，仍據地自立為"),
            new Entry("aw_hist_general_risk_label", "，风险 ", ", risk ", "，風險 "),
            new Entry("aw_hist_general_with_city", " 以", " used ", " 以"),
            new Entry("aw_hist_general_defected_to", " 投附", " to defect to ", " 投附"),
            new Entry("aw_hist_general_power_risk", "，拥兵风险 ", ", military power risk ", "，擁兵風險 "),
            new Entry("aw_hist_general_followed", " 随", " followed ", " 隨"),
            new Entry("aw_hist_general_changed_to", " 改投", " and switched allegiance to ", " 改投"),
            new Entry("aw_hist_general_supports", " 主张奉", " advocated restoring ", " 主張奉"),
            new Entry("aw_hist_general_restore_mid", " 复国，向", " and declared restoration war on ", " 復國，向"),
            new Entry("aw_hist_restoration_uprising_at", " \u4e8e", " raised a restoration army at ", " \u65bc"),
            new Entry("aw_hist_restoration_uprising_suffix", "\uff0c\u4e3e\u5175\u590d\u56fd\uff0c\u7eed\u63a5\u65e7\u56fd", " and renewed the fallen realm", "\uff0c\u8209\u5175\u5fa9\u570b\uff0c\u7e8c\u63a5\u820a\u570b"),
            new Entry("aw_hist_restoration_completed_suffix", " \u6536\u590d\u65e7\u5730\uff0c\u590d\u56fd\u544a\u6210", " recovered its old cores and completed the restoration", " \u6536\u5fa9\u820a\u5730\uff0c\u5fa9\u570b\u544a\u6210"),
            new Entry("aw_hist_restoration_failed_suffix", " \u590d\u56fd\u653f\u6743\u518d\u5ea6\u8986\u4ea1\uff0c\u5b97\u5ba4\u5ba3\u79f0\u5f85\u65f6\u800c\u52a8", " restoration regime fell again; its royal claims became dormant", " \u5fa9\u570b\u653f\u6b0a\u518d\u5ea6\u8986\u4ea1\uff0c\u5b97\u5ba4\u5ba3\u7a31\u5f85\u6642\u800c\u52d5"),
            new Entry("aw_hist_general_declare_war_risk", " 宣战，风险 ", ", risk ", " 宣戰，風險 "),
            new Entry("aw_hist_feudatory_became_prince", " 受封为藩王，就藩", " was enfeoffed as a feudatory prince at ", " 受封為藩王，就藩"),
            new Entry("aw_hist_feudatory_granted", " 封", " enfeoffed ", " 封"),
            new Entry("aw_hist_feudatory_as_prince_at", " 为藩王，就藩", " as a feudatory prince at ", " 為藩王，就藩"),
            new Entry("aw_hist_feudatory_city_count", "，辖城 ", ", governing cities: ", "，轄城 "),
            new Entry("aw_hist_feudatory_seat_became", " 成为", " became the seat of ", " 成為"),
            new Entry("aw_hist_feudatory_seat_suffix", " 的藩都，流官仍治其城", "'s feudatory while appointed governors retained city administration", " 的藩都，流官仍治其城"),
            new Entry("aw_hist_feudatory_inherited_person", " 承袭", " inherited the feudatory seated at ", " 承襲"),
            new Entry("aw_hist_feudatory_inherited_suffix", "藩，继任藩王", " and succeeded as feudatory prince", "藩，繼任藩王"),
            new Entry("aw_hist_feudatory_line_passed", "藩承袭：", " feudatory succession: ", "藩承襲："),
            new Entry("aw_hist_feudatory_line_to", "传于", " was succeeded by ", "傳於"),
            new Entry("aw_hist_feudatory_abolished_prefix", " 因宗支绝嗣，除", " abolished the heirless feudatory of ", " 因宗支絕嗣，除"),
            new Entry("aw_hist_feudatory_abolished_suffix", "藩，辖地复归中央", "; its lands returned to direct rule", "藩，轄地復歸中央"),
            new Entry("aw_hist_feudatory_revoked_prefix", " 下诏废除", " decreed the abolition of the feudatory at ", " 下詔廢除"),
            new Entry("aw_hist_feudatory_revoked_suffix", "藩，收回全部辖地，藩王废为庶人", "; all lands returned to direct rule and the prince was reduced to common status", "藩，收回全部轄地，藩王廢為庶人"),
            new Entry("aw_hist_feudatory_prince_revoked", " 被废藩并贬为庶人", " lost the feudatory and was reduced to common status", " 被廢藩並貶為庶人"),
            new Entry("aw_hist_feudatory_relocated_prefix", " 迁封", " relocated ", " 遷封"),
            new Entry("aw_hist_feudatory_relocated_from", "自", " from ", "自"),
            new Entry("aw_hist_feudatory_relocated_to", "至", " to ", "至"),
            new Entry("aw_hist_feudatory_prince_relocated", " 奉诏迁封至", " was relocated by decree to ", " 奉詔遷封至"),
            new Entry("aw_hist_feudatory_reclaimed_prefix", " 收回藩国辖城", " reclaimed the feudatory city ", " 收回藩國轄城"),
            new Entry("aw_hist_feudatory_reclaimed_suffix", "，复归流官直辖", " for direct appointed administration", "，復歸流官直轄"),
            new Entry("aw_hist_feudatory_prince_lost_city", " 奉诏交还辖城", " returned the feudatory city ", " 奉詔交還轄城"),
            new Entry("aw_hist_feudatory_revocation_intensity", "；削藩烈度 ", "; revocation intensity ", "；削藩烈度 "),
            new Entry("aw_hist_favor_order_proclaimed", "颁推恩令，集权进一阶；此后藩国承袭，中央逐代收城", "Proclaimed the Favor Order and raised centralization; future feudatory successions return land to direct rule", "頒推恩令，集權進一階；此後藩國承襲，中央逐代收城"),
            new Entry("aw_hist_favor_order_applied", " 依推恩令", " applied the Favor Order", " 依推恩令"),
            new Entry("aw_hist_favor_order_reclaimed", "收回", " and reclaimed ", "收回"),
            new Entry("aw_hist_favor_order_reclaimed_suffix", "，复置流官直辖", " under direct appointed administration", "，復置流官直轄"),
            new Entry("aw_hist_favor_order_autonomy", "削单城藩自治至", " and reduced single-seat autonomy to ", "削單城藩自治至"),
            new Entry("aw_hist_favor_order_prince_record", " 承袭时奉推恩令，藩权受削", " inherited under the Favor Order and lost feudatory authority", " 承襲時奉推恩令，藩權受削"),
            new Entry("aw_hist_era_changed", "改元 ", "Changed era to ", "改元 "),

            // Mandate text
            new Entry("aw_hist_mandate_changed_mid", " 天命变化 ", " Mandate changed by ", " 天命變化 "),
            new Entry("aw_hist_mandate_current", "，当前 ", ", now ", "，目前 "),
            new Entry("aw_hist_mandate_protected", " 受天命护持，低天命暂未崩解王朝", " was protected by the Mandate; low Mandate did not collapse the dynasty yet", " 受天命護持，低天命暫未崩解王朝"),
            new Entry("aw_hist_mandate_claimed_mid", " 受命称帝，建立", " claimed the Mandate and founded ", " 受命稱帝，建立"),
            new Entry("aw_hist_actor_claimed_mandate", " 受天命为帝", " became emperor by the Mandate", " 受天命為帝"),
            new Entry("aw_hist_edict_mandate_claimed_mid", "受命于天，膺图御宇；肇建",
                " received the Mandate of Heaven and founded ",
                "受命於天，膺圖御宇；肇建"),
            new Entry("aw_hist_edict_mandate_claimed_suffix", "，即皇帝位，布告天下。",
                "; its ruler ascended the imperial throne and proclaimed the settlement to all under Heaven.",
                "，即皇帝位，布告天下。"),
            new Entry("aw_hist_edict_actor_claimed_mandate", "膺受天命，即皇帝位，君临天下。",
                " received Heaven's Mandate and ascended the imperial throne.",
                "膺受天命，即皇帝位，君臨天下。"),
            new Entry("aw_hist_mandate_ritual", " 祭天整顿，重申天命", " performed rites and reaffirmed the Mandate", " 祭天整頓，重申天命"),
            new Entry("aw_mandate_decision_sacrifice_gamble", "赌大斋戒", "Gamble Grand Sacrifice", "賭大齋戒"),
            new Entry("aw_mandate_decision_sacrifice_moderate", "中庸斋戒", "Moderate Grand Sacrifice", "中庸齋戒"),
            new Entry("aw_mandate_decision_sacrifice_conservative", "保守斋戒", "Conservative Grand Sacrifice", "保守齋戒"),
            new Entry("aw_mandate_sacrifice_qualified", "合格", "qualified", "合格"),
            new Entry("aw_mandate_sacrifice_unqualified", "不合格", "unqualified", "不合格"),
            new Entry("aw_mandate_sacrifice_outcome_auspicious", "吉兆", "auspicious", "吉兆"),
            new Entry("aw_mandate_sacrifice_outcome_neutral", "平兆", "neutral", "平兆"),
            new Entry("aw_mandate_sacrifice_outcome_ominous", "凶兆", "ominous", "凶兆"),
            new Entry("aw_hist_sacrifice_performed", " 举行", " performed ", " 舉行"),
            new Entry("aw_hist_sacrifice_qualification_mid", "，礼官资格：", "; ritual qualification: ", "，禮官資格："),
            new Entry("aw_hist_sacrifice_result_mid", "，祭兆：", "; omen: ", "，祭兆："),
            new Entry("aw_hist_sacrifice_mandate_mid", "，天命", "; Mandate ", "，天命"),
            new Entry("aw_hist_mandate_core_added", " 纳入天命法理核心", " was added to Mandate legal cores", " 納入天命法理核心"),
            new Entry("aw_hist_mandate_lost_prefix", " 失去天命（", " lost the Mandate (", " 失去天命（"),
            new Entry("aw_hist_mandate_collapse", " 天命崩解，天下大乱", " suffered Mandate collapse; the realm fell into chaos", " 天命崩解，天下大亂"),
            new Entry("aw_hist_edict_mandate_lost_prefix", "德命既衰，天命去之；因",
                " lost Heaven's favor on account of ",
                "德命既衰，天命去之；因"),
            new Entry("aw_hist_edict_mandate_lost_suffix", "，正统告终，奉天之号自此而罢。",
                "; its orthodox Mandate ended and the imperial claim was relinquished.",
                "，正統告終，奉天之號自此而罷。"),
            new Entry("aw_hist_edict_mandate_collapse", "德失于天，纲纪遂紊；天命崩解，四方离叛，天下由是大乱。",
                " lost Heaven's favor and the order of the realm broke down; the Mandate collapsed and all under Heaven fell into disorder.",
                "德失於天，綱紀遂紊；天命崩解，四方離叛，天下由是大亂。"),
            new Entry("aw_hist_mandate_war_declared_mid", " 向 ", " launched a Mandate war against ", " 向 "),
            new Entry("aw_hist_mandate_war_declared_suffix", " 发起天命战争", "", " 發起天命戰爭"),
            new Entry("aw_hist_mandate_none", "当前没有天命王朝", "No current Mandate dynasty", "目前沒有天命王朝"),
            new Entry("aw_hist_mandate_map_realm", "天命国: ", "Mandate realm: ", "天命國："),
            new Entry("aw_hist_mandate_value", "天命值: ", "Mandate: ", "天命值："),
            new Entry("aw_hist_mandate_authority", "皇权: ", "Authority: ", "皇權："),
            new Entry("aw_hist_mandate_core_control", "法理控制: ", "Core control: ", "法理控制："),
            new Entry("aw_hist_mandate_inside", "天命体系", "inside Mandate system", "天命體系"),
            new Entry("aw_hist_mandate_outside", "体系之外", "outside system", "體系之外"),
            new Entry("aw_hist_mandate_current_zone", "当前区域: ", "Current zone: ", "目前區域："),
            new Entry("aw_hist_mandate_core_title", "天命法理", "Mandate Legal Core", "天命法理"),
            new Entry("aw_hist_mandate_no_core", "当前没有天命法理", "No current Mandate legal core", "目前沒有天命法理"),
            new Entry("aw_hist_mandate_core_city_count", "核心城市: ", "Core cities: ", "核心城市："),
            new Entry("aw_hist_mandate_original_core", "初始法理: ", "Original cores: ", "初始法理："),
            new Entry("aw_hist_mandate_control_ratio", "控制率: ", "Control: ", "控制率："),
            new Entry("aw_hist_mandate_current_kingdom", "当前国家: ", "Current realm: ", "目前國家："),
            new Entry("aw_hist_mandate_pointed_core_count", "指向国家拥有法理地: ", "Hovered realm cores: ", "指向國家擁有法理地："),
            new Entry("aw_hist_mandate_pointed_control", "指向国家控制率: ", "Hovered realm control: ", "指向國家控制率："),
            new Entry("aw_hist_mandate_core_status_controlled", "天命国直属法理", "Mandate realm direct core", "天命國直屬法理"),
            new Entry("aw_hist_mandate_core_status_vassal", "天命附庸控制法理", "Mandate vassal core", "天命附庸控制法理"),
            new Entry("aw_hist_mandate_core_status_lost", "失控法理", "Lost legal core", "失控法理"),
            new Entry("aw_hist_mandate_core_status_orphan", "无天命王朝法理", "Orphan legal core", "無天命王朝法理"),
            new Entry("aw_hist_mandate_source", "来源: ", "Origin: ", "來源："),
            new Entry("aw_hist_mandate_marker", "标识: ", "Marker: ", "標識："),
            new Entry("aw_hist_mandate_rebels", "义军: ", "Rebels: ", "義軍："),
            new Entry("aw_hist_mandate_foreign_occupation", "外族占领: ", "Foreign occupation: ", "外族佔領："),
            new Entry("aw_hist_mandate_uprising_count", " 起，最强 ", " uprisings, strongest ", " 起，最強 "),
            new Entry("aw_hist_mandate_city_count_mid", " 城，最高民怨 ", " cities, max unrest ", " 城，最高民怨 "),
            new Entry("aw_hist_none", "无", "none", "無"),
            new Entry("aw_hist_mandate_dynasty_suffix", "朝", " Dynasty", "朝"),
            new Entry("aw_hist_mandate_dynasty_default", "天命王朝", "Mandate Dynasty", "天命王朝"),
            new Entry("aw_hist_mandate_end_low_mandate", "天命过低", "Mandate too low", "天命過低"),
            new Entry("aw_hist_mandate_end_war_lost", "天命战争失败", "lost Mandate war", "天命戰爭失敗"),
            new Entry("aw_hist_mandate_end_kingdom_fell", "王朝灭亡", "dynasty destroyed", "王朝滅亡"),
            new Entry("aw_hist_mandate_end_replaced", "改朝换代", "dynasty replaced", "改朝換代"),
            new Entry("aw_hist_mandate_end_player_grant", "\u73a9\u5bb6\u8f6c\u6388\u5929\u547d", "Mandate transferred by player", "\u73a9\u5bb6\u8f49\u6388\u5929\u547d"),
            new Entry("aw_hist_mandate_end_generic", "结束", "ended", "結束"),

            // Ruler names and title-system event templates
            new Entry("aw_hist_title_awarded", "{0}获赐称号{1}",
                "{0} received the title {1}", "{0}獲賜稱號{1}"),
            new Entry("aw_hist_title_accession_era", "{0}即位并建元{1}称{2}",
                "{0} acceded and proclaimed the {1} era as {2}", "{0}即位並建元{1}稱{2}"),
            new Entry("aw_hist_title_voluntary_era", "{0}以{1}改元{2}",
                "{0} changed the era to {2} because of {1}", "{0}以{1}改元{2}"),
            new Entry("aw_hist_edict_accession_era", "{0}践祚，改元{1}，大赦天下；自今称{2}。",
                "{0} ascended the throne and proclaimed the {1} era; a general amnesty followed and the ruler would henceforth be styled {2}.",
                "{0}踐祚，改元{1}，大赦天下；自今稱{2}。"),
            new Entry("aw_hist_edict_imperial_proclamation",
                "制曰：{0}应天受命，称帝建元{1}；自今称{2}。",
                "Edict: {0}, receiving Heaven's charge, proclaimed the imperial title and inaugurated the {1} era; henceforth styled {2}.",
                "制曰：{0}應天受命，稱帝建元{1}；自今稱{2}。"),
            new Entry("aw_hist_edict_voluntary_era", "制曰：{0}因{1}，改元{2}，与民更始。",
                "Edict: {0} proclaimed the {2} era on account of {1}; the realm shall begin anew.",
                "制曰：{0}因{1}，改元{2}，與民更始。"),
            new Entry("aw_hist_title_state_name", "{0}立国号为{1}",
                "{0} established the state name {1}", "{0}立國號為{1}"),
            new Entry("aw_hist_title_retrospective", "{0}追尊{1}为{2}",
                "{0} retrospectively honored {1} as {2}", "{0}追尊{1}為{2}"),
            new Entry("aw_hist_title_shi_branch", "{0}由{1}分出{2}",
                "{0} founded {2} from {1}", "{0}由{1}分出{2}"),
            new Entry("aw_hist_official_edict_prefix", "制曰：", "Edict: ", "制曰："),
            new Entry("aw_hist_official_edict_mid", "考绩有闻，宜进", " has earned distinction in office and shall advance to ", "考績有聞，宜進"),
            new Entry("aw_hist_official_edict_office_mid", "，仍任", " while retaining the office of ", "，仍任"),
            new Entry("aw_hist_official_edict_suffix", "，勉修乃职，以副朝廷铨叙。", ". Fulfil the charge with diligence and justify the court's selection.", "，勉修乃職，以副朝廷銓敘。"),
            new Entry("aw_hist_official_evaluated", "考课评为", " was evaluated as ", "考課評為"),
            new Entry("aw_hist_official_rank_change", "，官阶", "; rank ", "，官階"),
            new Entry("aw_hist_official_kaoke_0", "上考", "Upper", "上考"),
            new Entry("aw_hist_official_kaoke_1", "中上", "Middle-upper", "中上"),
            new Entry("aw_hist_official_kaoke_2", "中中", "Middle", "中中"),
            new Entry("aw_hist_official_kaoke_3", "中下", "Middle-lower", "中下"),
            new Entry("aw_hist_official_kaoke_4", "下考", "Lower", "下考"),
            new Entry("aw_hist_court_petition_mid", "进献钱财干请于朝，耗资", " petitioned the court with a gift costing ", "進獻錢財干請於朝，耗資"),
            new Entry("aw_hist_court_petition_favor_mid", "，所得恩眷升至", "; court favor rose to ", "，所得恩眷升至"),
            new Entry("aw_hist_accession_book_prefix", "册曰：惟尔", "Accession book: ", "冊曰：惟爾"),
            new Entry("aw_hist_accession_book_mid", "承宗庙社稷，入奉", " is charged to inherit the ancestral rites and assume the rule of ", "承宗廟社稷，入奉"),
            new Entry("aw_hist_accession_book_suffix", "之祀，谨承大统，布政安民。", " and govern the people.", "之祀，謹承大統，布政安民。"),
            new Entry("aw_hist_nine_bestowments_prefix", "制曰：", "Edict: ", "制曰："),
            new Entry("aw_hist_nine_bestowments_mid", "总百揆而功高社稷，今于", " holds the chief offices and has rendered eminent service. The court of ", "總百揆而功高社稷，今於"),
            new Entry("aw_hist_nine_bestowments_suffix", "加九锡殊礼，以彰勋望；位极人臣，禅代之势由此而生。", " grants the Nine Bestowments in recognition; the minister now stands one step below the throne.", "加九錫殊禮，以彰勳望；位極人臣，禪代之勢由此而生。"),
            new Entry("aw_hist_ministerial_power_reached", "权柄升至", " reached ministerial power ", "權柄升至"),
            new Entry("aw_hist_ministerial_power_suffix", "，威权日重", "; authority over the court deepened", "，威權日重"),
            new Entry("aw_hist_ministerial_coup_success", "发动宫廷政变并夺取王位", " launched a palace coup and seized the throne", "發動宮廷政變並奪取王位"),
            new Entry("aw_hist_ministerial_coup_failed", "发动宫廷政变但被挫败", " launched a palace coup but was defeated", "發動宮廷政變但被挫敗"),
            new Entry("aw_hist_ministerial_power_label", "，权柄：", "; ministerial power: ", "，權柄："),
            new Entry("aw_title_reason_accession", "即位", "accession", "即位"),
            new Entry("aw_title_reason_restored_mandate", "重受天命", "restoration of the Mandate", "重受天命"),
            new Entry("aw_title_reason_autonomous_restoration", "自主复国", "autonomous restoration", "自主復國"),
            new Entry("aw_title_reason_major_victory", "大胜", "a major victory", "大勝"),
            new Entry("aw_title_reason_capital_recovered", "收复国都", "recovery of the capital", "收復國都"),
            new Entry("aw_title_reason_legal_core_recovered", "恢复法理故土", "recovery of legal core lands", "恢復法理故土"),
            new Entry("aw_title_reason_entered_revival", "中兴", "a dynastic revival", "中興"),
            new Entry("aw_title_reason_central_reform", "整饬中枢", "central reform", "整飭中樞"),
            new Entry("aw_title_reason_capital_relocated", "迁都", "relocation of the capital", "遷都"),
            new Entry("aw_title_reason_grand_sacrifice_blessing", "大祭获吉", "an auspicious grand sacrifice", "大祭獲吉"),
            new Entry("aw_title_reason_player_requested", "诏令", "imperial decree", "詔令"),
            new Entry("aw_title_reason_none", "即位", "accession", "即位"),

            // Posthumous title text and tooltip
            new Entry("aw_hist_event_conferred_posthumous", "赠谥", "Posthumous Conferment", "贈諡"),
            new Entry("aw_hist_conferred_posthumous_edict", "故{0}，{1}，赠谥{2}。", "The late {0}; {1}; is posthumously titled {2}.", "故{0}，{1}，贈諡{2}。"),
            new Entry("aw_hist_posthumous_title_label", "谥号：", "Posthumous title:", "諡號："),
            new Entry("aw_hist_posthumous_grade_label", "评等：", "Grade:", "評等："),
            new Entry("aw_hist_posthumous_dimension_label", "主因：", "Main factor:", "主因："),
            new Entry("aw_hist_posthumous_total_label", "总分：", "Total:", "總分："),
            new Entry("aw_hist_posthumous_civil_label", "民生 ", "Civil ", "民生 "),
            new Entry("aw_hist_posthumous_territory_label", "疆域 ", "Territory ", "疆域 "),
            new Entry("aw_hist_posthumous_war_label", "战功 ", "War ", "戰功 "),
            new Entry("aw_hist_posthumous_order_label", "秩序 ", "Order ", "秩序 "),
            new Entry("aw_hist_posthumous_ending_label", "结局 ", "Ending ", "結局 "),
            new Entry("aw_hist_posthumous_title_deposed", "，称为：", ", titled: ", "，稱為："),
            new Entry("aw_hist_posthumous_title_abdicated", "，退号为：", ", retirement title: ", "，退號為："),
            new Entry("aw_hist_posthumous_title_normal", "，谥为：", ", posthumously titled: ", "，諡為："),
            new Entry("aw_hist_posthumous_end_abdicated", "退位", "abdicated", "退位"),
            new Entry("aw_hist_posthumous_end_kingdom_fell", "国亡", "lost the realm", "國亡"),
            new Entry("aw_hist_posthumous_end_died", "驾崩", "died", "駕崩"),
            new Entry("aw_hist_posthumous_end_captured_slave", "被俘后身故", "died in captivity", "被俘後身故"),
            new Entry("aw_hist_posthumous_end_captured_executed", "\u88ab\u4fd8\u540e\u5904\u51b3", "executed after capture", "\u88ab\u4fd8\u5f8c\u8655\u6c7a"),
            new Entry("aw_hist_posthumous_grade_praise_high", "上谥", "High praise", "上諡"),
            new Entry("aw_hist_posthumous_grade_praise", "美谥", "Praise", "美諡"),
            new Entry("aw_hist_posthumous_grade_neutral", "平谥", "Neutral", "平諡"),
            new Entry("aw_hist_posthumous_grade_blame", "下谥", "Blame", "下諡"),
            new Entry("aw_hist_posthumous_grade_blame_high", "恶谥", "Severe blame", "惡諡"),
            new Entry("aw_hist_posthumous_unknown", "未知", "Unknown", "未知"),
            new Entry("aw_hist_posthumous_dimension_civil", "民生", "Civil affairs", "民生"),
            new Entry("aw_hist_posthumous_dimension_territory", "疆域", "Territory", "疆域"),
            new Entry("aw_hist_posthumous_dimension_war", "战功", "War merit", "戰功"),
            new Entry("aw_hist_posthumous_dimension_order", "秩序", "Order", "秩序"),
            new Entry("aw_hist_posthumous_dimension_ending", "结局", "Ending", "結局"),
            new Entry("aw_hist_posthumous_dimension_balanced", "综合", "Overall", "綜合"),
            new Entry("aw_hist_posthumous_reason_civil", "民生", "Civil", "民生"),
            new Entry("aw_hist_posthumous_reason_territory", " 疆域", " Territory", " 疆域"),
            new Entry("aw_hist_posthumous_reason_war", " 战功", " War", " 戰功"),
            new Entry("aw_hist_posthumous_reason_order", " 秩序", " Order", " 秩序"),
            new Entry("aw_hist_posthumous_reason_ending", " 结局", " Ending", " 結局"),
            new Entry("aw_hist_posthumous_reason_wins", "；胜", "; wins ", "；勝"),
            new Entry("aw_hist_posthumous_reason_losses", " 负", " losses ", " 負"),
            new Entry("aw_hist_posthumous_reason_city", " 城", " cities ", " 城"),
            new Entry("aw_hist_posthumous_reason_army", " 军", " army ", " 軍"),
            new Entry("aw_hist_posthumous_reason_reign", " 在位", " reigned ", " 在位"),
            new Entry("aw_hist_posthumous_reason_year", "年", " years", "年"),
            new Entry("aw_hist_posthumous_reason_death_cause", "；死因：", "; cause of death: ", "；死因："),

            // Mandate crisis history
            new Entry("aw_hist_mandate_succession_unstable", " 国本不稳，诸城一度有离心", " suffered succession instability; cities briefly wavered", " 國本不穩，諸城一度有離心"),
            new Entry("aw_hist_mandate_succession_damaged", " 国本不稳，天命因继承危机受损", " suffered succession instability and Mandate damage", " 國本不穩，天命因繼承危機受損")
            ,
            // War territory, goals, claims and core map text
            new Entry("aw_hist_core_mark_mid", " 将 ", " marked ", " 將 "),
            new Entry("aw_hist_core_mark_suffix", " 列为核心领土", " as core territory", " 列為核心領土"),
            new Entry("aw_hist_core_city_became_mid", " 成为 ", " became core territory of ", " 成為 "),
            new Entry("aw_hist_core_city_became_suffix", " 的核心领土", "", " 的核心領土"),
            new Entry("aw_hist_project_started_prefix", " 开始", " started ", " 開始"),
            new Entry("aw_hist_project_completed_prefix", " 完成", " completed ", " 完成"),
            new Entry("aw_hist_project_target_mid", "，目标为 ", ", target: ", "，目標為 "),
            new Entry("aw_hist_war_goal_set_mid", " 设定战争目标：", " set war goal: ", " 設定戰爭目標："),
            new Entry("aw_hist_war_goal_achieved_mid", " 达成战争目标：", " achieved war goal: ", " 達成戰爭目標："),
            new Entry("aw_hist_war_goal_defender_failed_mid", " 战败，被迫接受战争目标：", " was defeated and accepted war goal: ", " 戰敗，被迫接受戰爭目標："),
            new Entry("aw_hist_city_taken_by_goal_mid", " 因战争目标归于 ", " was transferred by war goal to ", " 因戰爭目標歸於 "),
            new Entry("aw_hist_war_goal_failed_mid", " 未能达成战争目标：", " failed war goal: ", " 未能達成戰爭目標："),
            new Entry("aw_hist_project_core", "制造核心", "Fabricate Core", "製造核心"),
            new Entry("aw_hist_project_strong_claim", "制造强宣称", "Fabricate Strong Claim", "製造強宣稱"),
            new Entry("aw_hist_project_weak_claim", "制造弱宣称", "Fabricate Weak Claim", "製造弱宣稱"),
            new Entry("aw_hist_project_prepare", "战争准备", "War Preparation", "戰爭準備"),
            new Entry("aw_hist_goal_take_core_city", "收复核心城市", "Reclaim Core City", "收復核心城市"),
            new Entry("aw_hist_goal_press_claim_city", "夺取宣称城市", "Press City Claim", "奪取宣稱城市"),
            new Entry("aw_hist_goal_press_strong_claim_city", "强宣称战争", "Strong Claim War", "強宣稱戰爭"),
            new Entry("aw_hist_goal_press_weak_claim_city", "弱宣称战争", "Weak Claim War", "弱宣稱戰爭"),
            new Entry("aw_hist_goal_take_mandate", "夺取天命", "Seize Mandate", "奪取天命"),
            new Entry("aw_hist_goal_mandate_conquest", "天命征服", "Mandate Conquest", "天命征服"),
            new Entry("aw_hist_goal_force_vassal", "强制臣服", "Force Vassalization", "強制臣服"),
            new Entry("aw_hist_goal_independence", "脱离宗主", "Break From Suzerain", "脫離宗主"),
            new Entry("aw_hist_goal_restore_kingdom", "复国", "Restore Kingdom", "復國"),
            new Entry("aw_hist_goal_no_cb", "强宣", "Forced War", "強宣"),
            new Entry("aw_hist_goal_zhulu_annexation", "逐鹿天下",
                "Contest All Under Heaven", "逐鹿天下"),
            new Entry("aw_hist_label_zhulu_war", "逐鹿战争", "Zhulu War",
                "逐鹿戰爭"),
            new Entry("aw_hist_goal_generic", "战争目标", "War Goal", "戰爭目標"),
            new Entry("aw_hist_goal_defender_win", "守方胜利", "defender victory", "守方勝利"),
            new Entry("aw_hist_goal_peace_unresolved", "议和未决", "peace unresolved", "議和未決"),
            new Entry("aw_map_focus_realm", "查看国：", "Focus realm: ", "查看國："),
            new Entry("aw_map_hover_realm", "当前国：", "Hovered realm: ", "目前國："),
            new Entry("aw_map_hover_city", "指向城市：", "Hovered city: ", "指向城市："),
            new Entry("aw_map_city_status", "城市状态：", "City status: ", "城市狀態："),
            new Entry("aw_map_progress", "进度：", "Progress: ", "進度："),
            new Entry("aw_map_core_cities", "核心城市：", "Core cities: ", "核心城市："),
            new Entry("aw_map_non_core", "非核心领土：", "Non-core territory: ", "非核心領土："),
            new Entry("aw_map_pending_core", "制造核心中：", "Fabricating cores: ", "製造核心中："),
            new Entry("aw_map_strong_claim", "强宣称：", "Strong claims: ", "強宣稱："),
            new Entry("aw_map_weak_claim", "弱宣称：", "Weak claims: ", "弱宣稱："),
            new Entry("aw_map_pending_claim", "制造宣称中：", "Fabricating claims: ", "製造宣稱中："),
            new Entry("aw_map_power_ratio", "国力比：", "Power ratio: ", "國力比："),
            new Entry("aw_map_reclaimable_core", "可收复核心：", "Reclaimable cores: ", "可收復核心："),
            new Entry("aw_map_pending", "制造中：", "Pending: ", "製造中："),
            new Entry("aw_map_can_mandate_conquest", "可发动天命征服", "Can launch Mandate conquest", "可發動天命征服"),
            new Entry("aw_map_can_force_vassal", "可发动附庸战争", "Can launch vassalization war", "可發動附庸戰爭"),
            new Entry("aw_map_can_restore", "可发动复国战争：持有亡国王室宣称 ", "Can launch restoration war: hosted royal claims ", "可發動復國戰爭：持有亡國王室宣稱 "),
            new Entry("aw_map_restore_blocked", "持有复国宣称，但目标被附庸体系或战争状态阻断", "Restoration claim exists but vassal system or war state blocks it", "持有復國宣稱，但目標被附庸體系或戰爭狀態阻斷"),
            new Entry("aw_map_can_no_cb", "可强宣，但会产生惩罚", "Can force war, with penalties", "可強宣，但會產生懲罰"),
            new Entry("aw_map_count_suffix", " 个", "", " 個"),
            new Entry("aw_map_status_core", "核心", "Core", "核心"),
            new Entry("aw_map_status_fabricate_core", "制造核心", "Fabricating Core", "製造核心"),
            new Entry("aw_map_status_non_core", "非核心领土", "Non-Core Territory", "非核心領土"),
            new Entry("aw_map_status_core_claim", "核心宣称", "Core Claim", "核心宣稱"),
            new Entry("aw_map_status_strong_claim", "强宣称", "Strong Claim", "強宣稱"),
            new Entry("aw_map_status_weak_claim", "弱宣称", "Weak Claim", "弱宣稱"),
            new Entry("aw_map_status_fabricate_strong_claim", "制造强宣称", "Fabricating Strong Claim", "製造強宣稱"),
            new Entry("aw_map_status_fabricate_weak_claim", "制造弱宣称", "Fabricating Weak Claim", "製造弱宣稱"),
            new Entry("aw_map_status_none", "无", "None", "無"),
            new Entry("aw_unknown_city", "某城", "unknown city", "某城"),

            // Shared biography and chronicle prose
            new Entry("aw_hist_person_born", " 出生", " was born", " 出生"),
            new Entry("aw_hist_figure_arrived", " 降临世间", " entered the world", " 降臨世間"),
            new Entry("aw_hist_person_died", " 逝世", " died", " 逝世"),
            new Entry("aw_hist_death_cause_prefix", "（死因：", " (cause: ", "（死因："),
            new Entry("aw_hist_death_cause_suffix", "）", ")", "）"),
            new Entry("aw_death_cause_acid", "酸蚀而死", "died from acid", "酸蝕而死"),
            new Entry("aw_death_cause_fire", "焚烧而死", "burned to death", "焚燒而死"),
            new Entry("aw_death_cause_age", "自然老死", "died of old age", "自然老死"),
            new Entry("aw_death_cause_starvation", "饥饿而死", "died of starvation", "飢餓而死"),
            new Entry("aw_death_cause_disease", "疾病而死", "died from disease", "疾病而死"),
            new Entry("aw_death_cause_eaten", "被吞食", "was eaten", "被吞食"),
            new Entry("aw_death_cause_weapon", "战斗身亡", "died in battle", "戰鬥身亡"),
            new Entry("aw_death_cause_poison", "中毒而死", "died from poison", "中毒而死"),
            new Entry("aw_death_cause_drowning", "溺亡", "drowned", "溺亡"),
            new Entry("aw_death_cause_water", "水中遇难", "died in water", "水中遇難"),
            new Entry("aw_death_cause_gravity", "坠落而死", "died from a fall", "墜落而死"),
            new Entry("aw_death_cause_explosion", "爆炸身亡", "died in an explosion", "爆炸身亡"),
            new Entry("aw_death_cause_divine", "神力所杀", "was slain by divine power", "神力所殺"),
            new Entry("aw_death_cause_metamorphosis", "异变消亡", "perished through metamorphosis", "異變消亡"),
            new Entry("aw_death_cause_mysterious", "神秘死亡", "died mysteriously", "神秘死亡"),
            new Entry("aw_death_cause_accident", "意外死亡", "died in an accident", "意外死亡"),
            new Entry("aw_death_cause_natural", "自然死亡", "died naturally", "自然死亡"),
            new Entry("aw_death_cause_unknown", "未知死因", "unknown cause of death", "未知死因"),
            new Entry("aw_death_cause_killed_by_prefix", "被 ", "killed by ", "被 "),
            new Entry("aw_death_cause_killed_by_suffix", " 击杀", "", " 擊殺"),
            new Entry("aw_hist_kingdom_renamed_mid", " 改国名为 ", " was renamed to ", " 改國名為 "),
            new Entry("aw_hist_war_attacker", "攻方", "attacker", "攻方"),
            new Entry("aw_hist_war_defender", "守方", "defender", "守方"),
            new Entry("aw_hist_war_victory_suffix", " 胜", " won", " 勝"),
            new Entry("aw_hist_war_result_peace", "议和", "White peace", "議和"),
            new Entry("aw_hist_war_result_merged", "合并", "Merged", "合併"),
            new Entry("aw_hist_war_result_inconclusive", "不分胜负", "No decisive victor", "不分勝負"),

            // Foreign occupation and cultural assimilation
            new Entry("aw_hist_foreign_slaves_mid", " 外族占领期间编入奴隶 ", " enslaved residents during foreign occupation: ", " 外族佔領期間編入奴隸 "),
            new Entry("aw_hist_foreign_count_suffix", " 名", " people", " 名"),
            new Entry("aw_hist_foreign_local_leader_mid", " 的本地城主 ", "'s local governor ", " 的本地城主 "),
            new Entry("aw_hist_foreign_replaced_mid", " 被", " was replaced by ", " 被"),
            new Entry("aw_hist_foreign_replaced_suffix", " 取代", "", " 取代"),
            new Entry("aw_hist_foreign_city_assimilated_mid", " 被同化为", " adopted the culture and language of ", " 被同化為"),
            new Entry("aw_hist_foreign_city_assimilated_suffix", " 的文化与语言", "", " 的文化與語言"),
            new Entry("aw_hist_foreign_kingdom_assimilated_mid", " 完成对", " completed the cultural assimilation of ", " 完成對"),
            new Entry("aw_hist_foreign_kingdom_assimilated_suffix", " 的文化同化", "", " 的文化同化"),
            new Entry("aw_hist_foreign_progress_mid", " 外族占领同化进度达到 ", " reached foreign-occupation assimilation progress of ", " 外族佔領同化進度達到 "),
            new Entry("aw_hist_occupation_type_pseudo_dynasty", "伪朝入据", "pseudo-dynastic occupation", "偽朝入據"),
            new Entry("aw_hist_occupation_type_foreign_entry", "外族入据", "foreign entry", "外族入據"),
            new Entry("aw_hist_occupation_type_foreign_occupation", "异文化占领", "foreign cultural occupation", "異文化佔領"),
            new Entry("aw_hist_foreign_city_occupied_mid", " 被", " was occupied by ", " 被"),
            new Entry("aw_hist_foreign_occupation_label_prefix", " ", " (", " "),
            new Entry("aw_hist_foreign_occupation_label_suffix", "", ")", ""),
            new Entry("aw_hist_foreign_kingdom_occupied_mid", " 占据 ", " occupied ", " 佔據 "),

            // Generals, rebels, claims and government transitions
            new Entry("aw_hist_general_appointed_person", " 以军功受任为大将", " was appointed general for military merit", " 以軍功受任為大將"),
            new Entry("aw_hist_general_appointed_kingdom_mid", " 任", " appointed ", " 任"),
            new Entry("aw_hist_general_appointed_kingdom_suffix", " 为大将", " as general", " 為大將"),
            new Entry("aw_hist_general_merit_reached", " 以军功闻名，军功达 ", " became renowned for military service; merit reached ", " 以軍功聞名，軍功達 "),
            new Entry("aw_hist_general_merit_accumulated", " 军功累至 ", " accumulated military merit of ", " 軍功累至 "),
            new Entry("aw_hist_mandate_rebel_rose_mid", " 于 ", " rose in ", " 於 "),
            new Entry("aw_hist_mandate_rebel_rose_suffix", " 起兵，称义军", " as a rebel army", " 起兵，稱義軍"),
            new Entry("aw_hist_mandate_rebel_city_mid", " 起兵反抗 ", " rose against ", " 起兵反抗 "),
            new Entry("aw_hist_mandate_rebel_leader", " 被推为义军领袖", " was acclaimed leader of the rebel army", " 被推為義軍領袖"),
            new Entry("aw_hist_mandate_rebel_claimed", " 义军受命，建立天朝", " claimed the Mandate and established an imperial court", " 義軍受命，建立天朝"),
            new Entry("aw_hist_mandate_rebel_emperor", " 以义军领袖身份受命称帝", " claimed the Mandate as rebel leader and became emperor", " 以義軍領袖身份受命稱帝"),
            new Entry("aw_hist_mandate_rebel_settled", " 义军战事结束，恢复普通政体", " ended the rebellion and restored ordinary government", " 義軍戰事結束，恢復普通政體"),
            new Entry("aw_hist_mandate_rebel_mobilized_mid", " 动员义军 ", " mobilized ", " 動員義軍 "),
            new Entry("aw_hist_mandate_rebel_mobilized_suffix", " 名", " rebels", " 名"),
            new Entry("aw_hist_royal_claim_host_mid", " 以", " launched a restoration war on behalf of ", " 以"),
            new Entry("aw_hist_royal_claim_host_suffix", " 的旧国血统发起复国战争，宣称恢复 ", " and claimed restoration of ", " 的舊國血統發起復國戰爭，宣稱恢復 "),
            new Entry("aw_hist_royal_claim_old_order_suffix", " 旧统", "'s former order", " 舊統"),
            new Entry("aw_hist_royal_claim_restored_mid", " 复建", " restored ", " 復建"),
            new Entry("aw_hist_royal_claim_suzerain_mid", "，奉", ", recognizing ", "，奉"),
            new Entry("aw_hist_royal_claim_suzerain_suffix", " 为宗主", " as suzerain", " 為宗主"),
            new Entry("aw_hist_royal_claim_gained_mid", " 获得 ", " gained a restoration claim to ", " 獲得 "),
            new Entry("aw_hist_royal_claim_gained_suffix", " 复国宣称", "", " 復國宣稱"),
            new Entry("aw_hist_royal_claim_inherited_mid", " 承续 ", " inherited a restoration claim to ", " 承續 "),
            new Entry("aw_hist_republic_ended", " 重新拥立君主，结束共和政体", " restored the monarchy and ended republican government", " 重新擁立君主，結束共和政體"),
            new Entry("aw_hist_republic_established", " 已无可立之君，改为共和政体", " had no eligible monarch and adopted republican government", " 已無可立之君，改為共和政體"),
            new Entry("aw_hist_slave_only_rebel_kingdom", " 因国中已无自由民可立，解奴籍并改编为义军", " had no free subject eligible to rule; slaves were freed and reorganized as a rebel army", " 因國中已無自由民可立，解奴籍並改編為義軍"),
            new Entry("aw_hist_slave_only_rebel_leader", " 解奴籍，被推为义军领袖", " was freed from slavery and acclaimed leader of the rebel army", " 解奴籍，被推為義軍領袖"),

            // Civil-service examinations and first appointments
            new Entry("aw_hist_civil_service_exam_opened_mid", "开科举行", " opened the ", "開科舉行"),
            new Entry("aw_hist_civil_service_exam_opened_year_mid", "，本届为世界第", " for world year ", "，本屆為世界第"),
            new Entry("aw_hist_civil_service_exam_opened_candidates_mid", "年，应试者", " with ", "年，應試者"),
            new Entry("aw_hist_civil_service_exam_opened_suffix", "人。", " candidates.", "人。"),
            new Entry("aw_hist_civil_service_qualified_mid", "于本届考试取得", " qualified as ", "於本屆考試取得"),
            new Entry("aw_hist_civil_service_qualified_year_mid", "资格，本届为世界第", " in world year ", "資格，本屆為世界第"),
            new Entry("aw_hist_civil_service_qualified_suffix", "年。", ".", "年。"),
            new Entry("aw_hist_civil_service_top_ranked_mid", "获定为", " was ranked as ", "獲定為"),
            new Entry("aw_hist_civil_service_top_ranked_year_mid", "，本届为世界第", " in world year ", "，本屆為世界第"),
            new Entry("aw_hist_civil_service_top_ranked_suffix", "年。", ".", "年。"),
            new Entry("aw_hist_civil_service_exam_completed_mid", "完成本届", " completed the ", "完成本屆"),
            new Entry("aw_hist_civil_service_exam_completed_year_mid", "定榜，本届为世界第", " roll for world year ", "定榜，本屆為世界第"),
            new Entry("aw_hist_civil_service_exam_completed_suffix", "年。", ".", "年。"),
            new Entry("aw_hist_civil_service_first_appointment_mid", "凭", " entered office as a ", "憑"),
            new Entry("aw_hist_civil_service_first_appointment_office_mid", "资格初授", " and received a first appointment as ", "資格初授"),
            new Entry("aw_hist_civil_service_first_appointment_suffix", "，正式入仕。", ".", "，正式入仕。"),

            // Xiaization, economy, technology and policy history
            new Entry("aw_hist_xiaized_city_mid", " 在", " adopted Xia institutions under ", " 在"),
            new Entry("aw_hist_xiaized_city_suffix", " 统治下行夏制，本地语言与血统不被强制改写", " without forcibly replacing local language or ancestry", " 統治下行夏制，本地語言與血統不被強制改寫"),
            new Entry("aw_hist_xiaization_entered", " 入据夏地，开始接入夏制度体系", " entered Xia lands and began adopting Xia institutions", " 入據夏地，開始接入夏制度體系"),
            new Entry("aw_hist_xiaization_presided_mid", " 主持", " presided over: ", " 主持"),
            new Entry("aw_hist_xiaization_appeased_mid", " 抚夏民，安抚入据城邑 ", " appeased Xia residents in occupied cities: ", " 撫夏民，安撫入據城邑 "),
            new Entry("aw_hist_xiaization_city_count_suffix", " 座", " cities", " 座"),
            new Entry("aw_hist_xiaization_level_foreign", "与夏地接触日深，开始知夏", "deepened contact with Xia lands and began learning Xia customs", "與夏地接觸日深，開始知夏"),
            new Entry("aw_hist_xiaization_level_pseudo", "采夏俗，可从入夏路线接入国策", "adopted Xia customs and opened the Xiaization policy path", "採夏俗，可從入夏路線接入國策"),
            new Entry("aw_hist_xiaization_level_rites", "采夏礼，将祭祀和朝仪改作夏制", "adopted Xia rites for sacrifice and court ceremony", "採夏禮，將祭祀和朝儀改作夏制"),
            new Entry("aw_hist_xiaization_level_institutions", "行夏制，接入夏地政体与律令", "adopted Xia government and law", "行夏制，接入夏地政體與律令"),
            new Entry("aw_hist_xiaization_level_dynasty", "成为入夏王朝", "became a Xiaized dynasty", "成為入夏王朝"),
            new Entry("aw_hist_xiaization_level_started", "开始入夏", "began Xiaization", "開始入夏"),
            new Entry("aw_hist_city_economy_role_mid", " 城市经济定型为 ", " developed an urban economy focused on ", " 城市經濟定型為 "),
            new Entry("aw_hist_city_economy_tax_mid", "，税收 ", "; tax contribution ", "，稅收 "),
            new Entry("aw_hist_city_economy_adjusted_mid", " 调整城市经济：", " adjusted the economy of ", " 調整城市經濟："),
            new Entry("aw_hist_city_economy_role_arrow", " -> ", " toward ", " -> "),
            new Entry("aw_hist_city_tech_completed_mid", " 完成科技 ", " completed technology ", " 完成科技 "),
            new Entry("aw_hist_city_tech_reached_capital_mid", "，先行传入", ", first reaching ", "，先行傳入"),
            new Entry("aw_hist_city_tech_capital_adopted_mid", " 首先采纳科技 ", " first adopted technology ", " 首先採納科技 "),
            new Entry("aw_hist_city_tech_adopted_mid", " 采纳科技 ", " adopted technology ", " 採納科技 "),
            new Entry("aw_hist_policy_kind_tech", "科技", "technology", "科技"),
            new Entry("aw_hist_policy_kind_decision", "决策", "decision", "決策"),
            new Entry("aw_hist_policy_kind_policy", "国策", "policy", "國策"),
            new Entry("aw_hist_policy_completed_mid", " 完成", " completed ", " 完成"),
            new Entry("aw_hist_policy_presided_mid", " 主持完成", " presided over completion of ", " 主持完成"),
            new Entry("aw_hist_policy_kind_separator", " ", " ", " "),
            new Entry("aw_hist_capital_moved_from", " 迁都，由", " moved the capital from ", " 遷都，由"),
            new Entry("aw_hist_capital_moved_to", "迁往", " to ", "遷往"),
            new Entry("aw_hist_royal_expansion_sent_mid", " 派", " sent ", " 派"),
            new Entry("aw_hist_royal_expansion_founded_mid", "开疆，建立", " to open new lands and found ", "開疆，建立")
        };
    }
}
